### PR TITLE
better mapping of Child and Dependent Care Expenses Credit

### PR DESCRIPTION
**Pull request by bodiyang**
Change of the mapping of the variable Child and Dependent Care Expenses Credit, to TAXSIM35.

`c07180` and `CDCC_refund` mapping value will be changed correspondingly

### CODE REVIEW

**Comment by jdebacker** [comment]
@bodiyang Thanks for looking at this.  Can you give some more context to what you are doing in this PR so we have it for the record?  Thanks!

**Comment by bodiyang** [comment]
There are two issues solved in this PR
(1)`c07180` takes the `f2441` as number of qualified child under 13, as in [calcfunctions.py](https://github.com/PSLmodels/Tax-Calculator/blob/b847e4ffb6144bc462d3e680004a40ca2c5ac806/taxcalc/calcfunctions.py#L2168)

When mapping from TAXSIM to Tax-Calc, we only used to have `dep13` -> `nu13`, but no mapping for `f2331`, that's why `c07180` was zero out in Tax-Calc.

After adding the mapping of `f2441`, Tax-Calc is able to produce the correct ` c07180` result.


(2)Child and Dependent Care Credit is refundable for 2021, not refundable for the rest years. `c07180` is the non-refundable CDCC, so is zero in 2021. In order to compare the CDCC amount in 2021 with TAXSIM, we need to map `c07180` t0 `CDCC_refund` in 2021

**Comment by bodiyang** [comment]
> Perhaps you should shift to using the dependent age variables in taxsim35 (age1,age2, age3) which lets taxsim calculate the number of eligible children. Daniel Feenberg
> […](#)
> On Mon, 5 Feb 2024, Bodi Yang wrote: There are two issues solved in this PR (1)`c07180` takes the `f2441` as number of qualified child under 13, as in [calcfunctions.py](https://github.com/PSLmodels/Tax-Calculator/blob/b847e4ffb6144bc462d3e680004a40ca2c5ac806/taxcalc/calcfunctions.py#L2168) When mapping from TAXSIM to Tax-Calc, we only used to have `dep13` -> `nu13`, but no mapping for `f2331`, that's why `c07180` was zero out in Tax-Calc. After adding the mapping of `f2441`, Tax-Calc is able to produce the correct ` c07180` result. (2)Child and Dependent Care Credit is refundable for 2021, not refundable for the rest years. `c07180` is the non-refundable CDCC, so is zero in 2021. In order to compare the CDCC amount in 2021 with TAXSIM, we need to map `c07180` t0 `CDCC_refund` in 2021 -- Reply to this email directly or view it on GitHub: [#2710 (comment)](https://github.com/PSLmodels/Tax-Calculator/pull/2710#issuecomment-1927129929) You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>

Thanks for the note Daniel. This PS's issue is a fix on the Tax-Calculator side. 

~ I have already mapped the TAXSIM age variables (age1,age2, age3) to Tax-Calc age variables

**Comment by jdebacker** [comment]
@bodiyang I think this is a nice mapping to make for comparisons to TAXSIM.  Thank you for the PR!

**Pull request merged**
