### PR TITLE
Don't index SALT cap (ID_AllTaxes_c)

### LINKED ISSUE #2387: SALT cap (ID_AllTaxes_c) should not be indexed to inflation
Reported in https://github.com/PSLmodels/Tax-Brain/issues/101

### PR DESCRIPTION
**Pull request by MaxGhenis**
Fixes #2387

### CODE REVIEW

**Comment by MaxGhenis** [comment]
This is [failing](https://travis-ci.com/PSLmodels/Tax-Calculator/jobs/266401727) the TCJA round trip test:
>E           ValueError: 
E           Round-trip-reform and current-law-policy param values differ for:
E             ID_AllTaxes_c in 2020 : rtr=[10000.0, 10000.0, 5000.0, 10000.0, 10000.0] clp=[10414.17, 10414.17, 5207.08, 10414.17, 10414.17]

Seems like TCJA is stuck with the indexed values, but I can't find how to change that (or in general how to change whether a value is indexed in a reform).

cc @MattHJensen in case you'd started working on this

**Comment by MattHJensen** [comment]
@MaxGhenis, I believe [these lines](https://github.com/PSLmodels/Tax-Calculator/blob/9272ffdc2ee513885067d55d282813ec421a533f/taxcalc/policy_current_law.json#L1492-L1498) need to be all 10000s. 

The ceiling expires in 2026, so we have to specify all values out to 2026 in order to specify the 9e+99 in that year.

The `indexed` value that you changed only applies after the last specified parameter value, so in this case it only begins affecting parameter values in 2027 and doesn't end up making any difference given that we're already at 9e+99.

**Comment by MaxGhenis** [comment]
Thanks @MattHJensen, all set now.

**Comment by MaxGhenis** [comment]
Odd, there was a conda error after updating `pufcsv_agg_expect.csv`. It doesn't appear to have anything to do with that update.
```
$ conda create -n taxcalc-dev python=$TRAVIS_PYTHON_VERSION;
Fetching package metadata ...An unexpected error has occurred.
```

Per https://github.com/conda/conda/issues/3935#issuecomment-263756320 (3 years old) the recommended fix is to use
```
CONDA_SSL_VERIFY=false conda update pyopenssl
```
Anyone hit this before or know how to do it for Travis? If not I can ask on that issue.

**Comment by MattHJensen** [comment]
Thanks a lot, @MaxGhenis. This looks good to me. Good for me to merge from your end?

**Comment by MaxGhenis** [comment]
Yep!

**Comment by MaxGhenis** [comment]
Sorry I wanted to amend a previously borked commit message, didn't expect it to re-trigger tests. No code has changed so tests should succeed soon.

**Comment by MaxGhenis** [comment]
OK all set for real now!

**Comment by MattHJensen** [comment]
Thanks, Max. Merging.

**Pull request merged**
