### PR TITLE
PerformanceWarning fix

### PR DESCRIPTION
**Pull request by jackisace**
odf copied on every pass to maintain data fidelity.

### CODE REVIEW

**Comment by jackisace** [comment]
I have copied the odf dataframe at the end of the loop to maintain fidelity.

**Comment by jdebacker** [comment]
@jackisace Thanks for this PR and your first contribution to Tax-Calculator!  Your suggested change looks good to me and fixes the warnings that I and others were seeing. 

I'll leave this PR open for another 24 hours and merge if there are no further comments.

**Comment by jdebacker** [comment]
Thanks again @jackisace.  Merging.

**Comment by jackisace** [comment]
@jdebacker happy to help

😊

**Pull request merged**
