### PR TITLE
Add new social security tax option for capital income 

### PR DESCRIPTION
**Pull request by Peter-Metz**
This pull request adds a parameter called `SS_cg_thd` which can be used for a policy that imposes OASDI tax on capital income above a certain threshold. This additional social security tax would be on top of the existing capital gains tax.

I would appreciate a brief review of the variables used in the tax logic and the implementation of the code. Namely, is `c23650` the appropriate variable to represent capital income?

### CODE REVIEW

**Comment by martinholmer** [comment]
@Peter-Metz said in Tax-Calculator pull request #2356:
> This pull request adds a parameter called `SS_cg_thd` which can be used for a policy that imposes OASDI tax on capital income above a certain threshold.

Where does this idea come from?  Who is proposing such a change in OASDI payroll tax policy?  
Can you point us to the SSA Office of the Chief Actuary's memo that analyzes this reform proposal?

**Comment by MattHJensen** [comment]
@Peter-Metz, thanks a lot for working on this! 

The original request that I passed on to you was:

> "how much revenues would be raised if capital income were subject to OASDI taxes for people earning $200K ($250K couple)?"

After seeing your pull request, I was motivated to send these questions about the reference to "earnings":

> - I presume you mean the current definition of earnings that is used for the social security tax computation. Is that correct?
> 
> - Currently, OASDI is an individual-based tax, partly because employers don't know about spousal earnings. Are you ok dropping the $250k joint specification and leaving it at $200k per earner? 
> - Similarly, we'll need to allocate joint capital income to both earners -- are you ok with assuming a 50/50 split for now? 
> 
> - How does this interact with the current social security earnings cap? Is it that my SS earnings are only taxed up to the cap; but, if my SS earnings are over $200k, then all of my capital income is subject to the tax, uncapped? 

The answer to all questions was, "yes." 

@Peter-Metz, I hope this helps with your next round of work on this.  The new documentation for adding parameters to Tax-Calculator is also relevant and worth checking out. (https://github.com/PSLmodels/Tax-Calculator/pull/2358/files#diff-6a3371457528722a734f3c51d9238c13R11.)

---

To answer @martinholmer's questions: 

> Where does this idea come from?

The idea is from contact of mine who is a senior advisor to Democrat politicians and policymakers. 

> Can you point us to the SSA Office of the Chief Actuary's memo that analyzes this reform proposal?

There is no such memo. 
 
--- 

If anyone has additional questions you'd like me to ask the idea originator, please let me know.

**Comment by Peter-Metz** [comment]
@martinholmer, I saw the changes to the contributor guidelines in #2358, and would be happy to follow the new procedure. I will open an issue once I have modified recipe 6 in the cookbook.

@MattHJensen thanks for the clarification on the reform

**Comment by martinholmer** [comment]
@MattHJensen,  Thanks for providing background on PR #2356 in [this comment](https://github.com/PSLmodels/Tax-Calculator/pull/2356#issuecomment-507058418).
This background information will help me answer @Peter-Metz's question in a subsequent comment.

**Comment by martinholmer** [comment]
In PR #2356, @Peter-Metz asked this question:
> [I]s c23650 the appropriate variable to represent capital income?

In a word, the answer to your question is no.  Capital **income** is far broader than capital **gains**, in that it includes interest income and dividend income.

Current law tax policy already includes a tax on the **capital income** received by filing units with income above a threshold, which is called the Net Investment Income Tax (NIIT).  The NIIT threshold values are exactly what the requestor specifies: that is, $250,000 for married filing jointly and $200,000 for single and head of household filers, as you can see from this listing in the Tax-Calculator User Guide.

Screen Shot 2019-07-01 at 6 53 12 AM


The current-law NIIT rate is 0.038.  We have a JSON reform file for the [Sanders-DeFazio proposal](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/reforms/SandersDeFazio.json) that includes a provision that adds the **employee** OASDI tax rate (0.062) to the existing 0.038, making the NIIT rate 0.100.

My best guess is that the requestor wants a revenue estimate of that provision in the Sanders-DeFazio proposal.  You can provide the requestor with such a revenue estimate using the current (2.4.2) version of Tax-Calculator.  

If the requestor says the thresholds should be **earnings** not income (AGI), you might want to explain to him, using some simple examples, why using earnings (not income) for the threshold would be very difficult for him to defend.  For example, why should a person with ten million dollars in dividends and no job be exempt from the new tax on capital income?

Also, if the requestor says this new tax must be part of the FICA payroll tax, you might want to explain to him, using some simple examples, why this would put employers in a difficult position.  For example, why would any employer want to hire the person described in the prior paragraph at a salary of $200,000 or more?  In that case, the employer would have to pay $620,000 as the employer share of the new capital income taxes.  And, of course, there are the administrative problems that Matt mentioned: the employer knows the employee's compensation, not the employee's capital income.

**Comment by MattHJensen** [comment]
Thanks @martinholmer for the excellent observations. I will relay these suggestions to the requestor and report back here.

**Comment by MattHJensen** [comment]
The requestor thought that the concerns @martinholmer raised about doing this via the FICA system were, "very persuasive," and he agreed that it would be better to just add 6.2% to the NIIT, as in Sanders-DeFazio.  

@Peter-Metz could you close this PR and then tee up a Tax-Brain preset on COMP that adds the 6.2% to the NIIT rate and sets the behavior assumption at values cited in the docs?

**Comment by Peter-Metz** [comment]
@MattHJensen Will do. Closing this PR.

**Pull request closed without merging**
