### PR TITLE
Consolidated Appropriations Act of 2021

### PR DESCRIPTION
**Pull request by jdebacker**
This PR adds the recovery rebate credits from the Consolidated Appropriations Act of 2021 to the `policy_current_law.json` file, per the discussion in Issue #2591.

### CODE REVIEW

**Comment by jdebacker** [comment]
A score of this change from Tax-Calculator:
|         |     2020 |   2021 |   2022 |   2023 |   2024 |   2025 |   2026 |   2027 |   2028 |   2029 |   2030 |   2021-2030 |
|:--------|---------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|------------:|
| IIT     | -181.056 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |    -181.056 |
| Payroll |    0     |      0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |       0     |

And from JCT:

|         |     2020 |   2021 |   2022 |   2023 |   2024 |   2025 |   2026 |   2027 |   2028 |   2029 |   2030 |   2021-2030 |
|:--------|---------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|------------:|
| IIT     | 0 |      -165.698 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |    -165.698 |
| Payroll |    0     |      0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |      0 |       0     |

**Comment by jdebacker** [comment]
@Peter-Metz If you have time, can you give this PR a quick review?  I will update cached results to pass tests if you think these changes to `policy_current_law.json` are correct.

Thanks!

**Comment by Peter-Metz** [comment]
Happy to take a look @jdebacker. I'll comment back here in the next day or two

**Comment by Peter-Metz** [comment]
Hi @jdebacker and @amshoulders, just a couple of minor questions about this PR and #2586, which adds the parameters updated in this PR.

First, it seems like an update to the [first stimulus payment](https://www.irs.gov/newsroom/questions-and-answers-about-the-first-economic-impact-payment-topic-c-calculating-my-first-economic-impact-payment) scrapped the 5% phaseout rate for a phaseout end of $198,000 (married), $136,500 (hoh), $99,000 (single) plus $10,000 for each qualifying child. Currently, the tax logic applies a 5% phaseout to this payment.

Second, I see that `RRC_ps` for widows is $75,000 in 2020 and $150,000 in 2021. From looking at the IRS update (same link as above) it kind of seems that the bump from $75,000 to $150,000 works retroactively. So maybe 2020 should also be $150,000? I'm not really sure here.

Finally, I wonder if it would improve readability and give us flexibility wrt the phaseouts if we calculated the three payments separately within calcfunctions. On the other hand, this would add more parameters. Curious to hear what @jdebacker and @amshoulders think.

**Comment by jdebacker** [comment]
@Peter-Metz Thank you for this review!  I had not see those updates for widows, so I appreciate you pointing those out.


> First, it seems like an update to the first stimulus payment scrapped the 5% phaseout rate for a phaseout end of $198,000 (married), $136,500 (hoh), $99,000 (single) plus $10,000 for each qualifying child. Currently, the tax logic applies a 5% phaseout to this payment.

My reading of the update is that the 5% phaseout still applies.  They are just noting that the end of the phase out (where benefits are zero) jumps by $10,000 for each qualifying child.  This is because payments increase by $500 for each child and for that $500 to go to zero at a 5% rate, it takes another $10,000 in income above the phaseout.

e.g., take the example filing unit from [the IRS Q&A](https://www.irs.gov/newsroom/questions-and-answers-about-the-first-economic-impact-payment-topic-c-calculating-my-first-economic-impact-payment) that is married, filing jointly and has one child.  This filing unit gets a payment of $2,900, which begins to phase at an income above $150,000.  If phased out at a 5% rate, the payment reaches zero at an income of $150,000 + $2,900/0.05 = $208,000.  If the married, filing jointly unit has 2 qualifying children, the payment would have been $3,400, which would phaseout at 5% and reach zero at $150,000 + $3,400/0.05 = $218,000.  With three kids, payments would reach zero at $228,000, etc.

Note also that the 5% phaseout is explicitly in the Consolidated Appropriations Act:

Screen Shot 2021-06-03 at 10 09 29 PM


> Second, I see that RRC_ps for widows is $75,000 in 2020 and $150,000 in 2021. From looking at the IRS update (same link as above) it kind of seems that the bump from $75,000 to $150,000 works retroactively. So maybe 2020 should also be $150,000? I'm not really sure here.

My reading is the same as you -- the phaseout start for widows should increase to $150,000.  I just pushed a commit to change this.

> Finally, I wonder if it would improve readability and give us flexibility wrt the phaseouts if we calculated the three payments separately within calcfunctions. On the other hand, this would add more parameters. Curious to hear what @jdebacker and @amshoulders think.

Following pass suggestions, I think it's best to minimize the number of parameters.  I believe we are able to capture these provisions well and I'm not sure we could do it with any fewer parameters.

**Comment by Peter-Metz** [comment]
That all sounds great @jdebacker. After the tests are updated, this looks good to me.

**Comment by jdebacker** [comment]
Thanks @Peter-Metz.  I'm going to let @MattHJensen finish off PR #2593 first and then I'll update this branch and the tests.

**Comment by MattHJensen** [comment]
Looks good, @jdebacker. Thanks for the contribution. Thanks for the review, @Peter-Metz.

**Pull request merged**
