### PR TITLE
TAXSIM-32 validation update 

### PR DESCRIPTION
**Pull request by chusloj**
This PR updates the validation code for [TAXSIM-27](https://users.nber.org/~taxsim/taxsim27/) to use the new [TAXSIM-32](https://users.nber.org/~taxsim/taxsim32/) model.

### CODE REVIEW

**Comment by chusloj** [comment]
The prep files have been modified to accommodate TAXSIM-32. Notes:

- `taxsim_input.py` was updated to include the 5 new variables (vars 28-32) from TAXSIM-32
- `prepare_taxcalc_input.py` only had variables 28 (S-corp QBI income) and 30 (SSTB flag) mapped to Tax-Calculator input, but I'd like some input on modifying variables to adjust for QBI deductions. `calcfunctions.py` shows that QBI deductions are calculated using output variables.

A new shell file for TAXSIM-32 was also created for testing, and `input_setup.py` was created to automate the FTP retrieval of the TAXSIM-32 output, data cleaning and zipping the files.

For both the 2017 and 2018 assumption sets, set `b` now includes the SSTB flag for the `PT_SSTB_income` variable, and S-corp QBI income under the `e26270` variable. Still thinking about how to incorporate the S-Corp QBI deductions using only the input variables.

Finally, the `taxdiff-actual` and `README` files haven't been updated to reflect the status of the diffs or the introduction of new variables into the assumption sets. I'd like to update those after review.

@Peter-Metz

**Comment by Peter-Metz** [comment]
@chusloj thanks a lot of the PR. I think the first step is to lock down the translation from taxsim32 variables (in particular variables 28-32) to Tax-Calculator variables. Here is my first stab (building off what you have already done):

|Taxsim32 |Tax-Calculator   |
|:-:|:-:|
| scorp | [e26270](https://pslmodels.github.io/Tax-Calculator/guide/input_vars.html#e26270) |
| pbusinc | [e00900p](https://pslmodels.github.io/Tax-Calculator/guide/input_vars.html#e00900p) |
| sbusinc | [e00900s](https://pslmodels.github.io/Tax-Calculator/guide/input_vars.html#e00900s) |
| if (pprofinc + sprofinc)>0 | [PT_SSTB_income](https://pslmodels.github.io/Tax-Calculator/guide/input_vars.html#pt-sstb-income)=1, else 0 |

Maybe @MattHJensen or @kpomerleau have some input?

Taxsim32 definitions:

**scorp:** Active S-Corp income (is QBI). (Guaranteed S-corp partner profits and limited partner compensation are taxed as wages, not here).
**pbusinc:** Primary Taxpayer's Qualified Business Income (QBI) subject to a preferential rate without phaseout. Subject to SECA and Medicare additional Earnings Tax.
**pprofinc:** Primary Taxpayer's Specialized Service Trade or Business service (SSTB) with a preferential rate subject to claw-back. Subject to SECA and Medicare Additional Earnings Tax.
**sbusinc:** Spouse's QBI. Must be zero for non-joint returns.
**sprofinc:** Spouse's SSTB. Must be zero for non-joint returns.

**Comment by feenberg** [comment]
If this is about my online tax calculator, I have some updated 
instructions at:

    http://www.nber.org/taxsim/taxsim32/taxsim-ftp.html

that describes the ftp, ssh and http interfaces to taxsim32. There is also

   http://www.nber.org/taxsim/taxsim32/install.html

that describes how to install a local version. This may be of interest. 
Call or write if you have questions or suggestions.

Daniel Feenberg
617-863-0343

**Comment by MattHJensen** [comment]
@Peter-Metz, did your recent Tax-Cruncher work give you any further insights here?

**Comment by Peter-Metz** [comment]
I think the mapping in [this comment](https://github.com/PSLmodels/Tax-Calculator/pull/2453#issuecomment-675066952) still makes sense.

My remaining question is how TAXSIM-32 calculates the phase-out of the QBI deduction, which can be dependent on W-2 wages paid by the filer's business and/or the filer's amount of qualified property. Maybe @feenberg has insight?

**Comment by feenberg** [comment]
Taxsim32 assumes sufficient wage and capital income to avoid the phaseout. 
That is made clear in the documentation only in the last week - we hadn't 
even thought much about the issue but Martin raised it and I wrote to CBO 
for their preference. I go this back from Ed Harris:

>Hi Dan.  I asked a couple of colleagues about the binary choice between 
>assuming 1) no taxpayer is subject to the wage/capital restriction or 
>whether 2) all taxpayers are fully subject to the limitations (i.e, treat 
>them as having zero wage expense and no capital).  The consensus here is 
>that underestimate from option #2 would be larger than the overestimate 
>from option #1.

I picked #1 largely because I don't want to add any more variables that 
almost no user will have information about.

Dan

**Comment by Peter-Metz** [comment]
Thanks very much for the explanation @feenberg.

@MattHJensen -- Relatedly, I think offering both wage/capital options could be a good Tax-Calculator feature. Currently, Tax-Calculator assumes option 2) (i.e. all taxpayers are fully subject to wage and capital limitations). Instead of imputing values for these parameters, we could have a new boolean parameter that allows users to choose between the two options in Dan's comment.

**Comment by MattHJensen** [comment]
>  Relatedly, I think offering both wage/capital options could be a good Tax-Calculator feature. This makes sense to me, too. Is this something you'd be interested in working on?

**Comment by Peter-Metz** [comment]
@MattHJensen sure thing

**Comment by MattHJensen** [comment]
@chusloj, could you please update the status of this PR when you have an opportunity? Does the new QBI switch allow any further progress?

**Comment by chusloj** [comment]
@MattHJensen The new QBI Switch does not affect results in the diff file.

**Comment by Peter-Metz** [comment]
>The new QBI Switch does not affect differences between any variables in the diff file.

I think this is because the business income variables (Taxsim vars 28-32) are set to zero in the assumption dictionary (`adict`, created in `taxsim_input.py`).

**Comment by chusloj** [comment]
> business income variables (Taxsim vars 28-32) are set to zero in the assumption dictionary

@Peter-Metz My bad, I thought we given those variables nonzero values for the `b` and `c` assumption sets.

**Comment by chusloj** [comment]
In the coming weeks, the bash/shell processing scripts will be updated to Python. Additionally, @jdebacker has suggested some additional functionality that could make the validation output more useful and tractable.

**TODO**:
- [ ] Update all bash/shell processing files (`.sh`, `.awk`, `.tcl`) to Python
- [ ] Add functionality suggested by @jdebacker to the newly Python-formatted processing files:
    - [ ] More human readable output
    - [ ] Actually displaying which records have the maximum difference out of all records checked for a given variable

**Comment by chusloj** [comment]
###

**Comment by chusloj** [comment]
`taxsim_input.py` and `prepare_taxcalc_input.py` have been updated to accommodate input for the QBI variables (#28-32) in TAXSIM-32.

Below is the output of the difference between Tax-Calculator and TAXSIM-32 for the `b` assumption set in 2018:

``` bash
TAXDIFF:ovar,#diffs,#smdiffs,maxdiff[id]=  6  67638  67638     -0.30 [14299]
TAXDIFF:ovar,#diffs,#smdiffs,maxdiff[id]=  7  46049      1    -55.00 [91966]
      #big_vardiffs_with_big_inctax_diff=            46048
TAXDIFF:ovar=                              9  no-diffs
TAXDIFF:ovar,#diffs,#smdiffs,maxdiff[id]= 10  99931    156 -350001.98 [99038]
      #big_vardiffs_with_big_inctax_diff=            99774
TAXDIFF:ovar=                             11  no-diffs
TAXDIFF:ovar,#diffs,#smdiffs,maxdiff[id]= 12      5      0 -10980.15 [86602]
      #big_vardiffs_with_big_inctax_diff=                5
TAXDIFF:ovar=                             14  no-diffs
TAXDIFF:ovar=                             15  no-diffs
TAXDIFF:ovar=                             16  no-diffs
TAXDIFF:ovar=                             17  no-diffs
TAXDIFF:ovar,#diffs,#smdiffs,maxdiff[id]= 18 100000      1 -402620.99 [27456]
      #big_vardiffs_with_big_inctax_diff=            99998
TAXDIFF:ovar,#diffs,#smdiffs,maxdiff[id]= 22   9067     12   8500.00 [889]
      #big_vardiffs_with_big_inctax_diff=             9055
TAXDIFF:ovar,#diffs,#smdiffs,maxdiff[id]= 23      8      0   2157.88 [42056]
      #big_vardiffs_with_big_inctax_diff=                8
TAXDIFF:ovar=                             24  no-diffs
TAXDIFF:ovar=                             25  no-diffs
TAXDIFF:ovar,#diffs,#smdiffs,maxdiff[id]= 26 100000      1 -350000.00 [44031]
      #big_vardiffs_with_big_inctax_diff=            99998
TAXDIFF:ovar,#diffs,#smdiffs,maxdiff[id]= 27   5513      0  13628.83 [99720]
      #big_vardiffs_with_big_inctax_diff=             5513
TAXDIFF:ovar,#diffs,#smdiffs,maxdiff[id]= 28 100000      2 -130941.73 [27456]
      #big_vardiffs_with_big_inctax_diff=            99997
TAXDIFF:ovar,#diffs,#smdiffs,maxdiff[id]=  4 100000      1 -130262.99 [75369]
                       #big_inctax_diffs=            99999
```

Column descriptions are laid out in the first column of each observation where `ovar` is the variable name from TAXSIM-32.
Between this 2018 `b` assumption set output and the output with same assumption set and year excluding the QBI parameters, below are the variables which have notable differences in the number of differing records:

| `ovar` | TAXSIM-32 variable number | TAXSIM-32 variable name | Description |
|-|-|-|-|
| 7 | 6 | sage | Age of spouse |
| 10 | 9 | dep17 | Number of children under 17 for the entire tax year (Child Credit) |
| 18 | 17 | otherprop | Other property income subject to NIIT |
| 26 | 25 | otheritem | Other Itemized deductions that are a preference for the Alternative Minimum Tax |
| 27 | 26 | childcare | Child care expenses. |
| 28 | 27 | mortgage | Deductions not included in item 25 and not a preference for the AMT |

**Comment by Peter-Metz** [comment]
Hi @chusloj. Now that the QBI variables are factored into the validation, you may want to flip the `PT_qbid_limit_switch` to False in `taxsim32/taxsim_emulation.json`. Curious to hear if that does the trick.

**Comment by chusloj** [comment]
@Peter-Metz with `PT_qbid_limit_switch` set to `False`, here are the variables that changed:

| Variable | Old value | New value |
|-|-|-|
| 7 (Marginal federal income tax rate) | 46069 | 46032 |
| 27 (Federal AMT liability) | 5513 | 8368 |

All other variables didn't change.

**Comment by chusloj** [comment]
@Peter-Metz with `PT_qbid_limit_switch` set to `False`, here are the variables that changed:

| Variable | Old value from [table above](https://github.com/PSLmodels/Tax-Calculator/pull/2453#issuecomment-759748429) | New value |
|-|-|-|
| 7 (Marginal federal income tax rate) | 46069 | 46032 |
| 27 (Federal AMT liability) | 5513 | 8368 |

All other variables didn't change.

**Comment by chusloj** [comment]
@jdebacker and others, the TAXSIM-32 validation process has been transferred from `bash` to Python. Human-readable output for the differences between TAXSIM-32 and Tax-Calculator are now printed at runtime and include the maximum difference, the location of that difference in the TAXSIM/TaxCalc data frames and values at that index from both data frames.

To run the validation process, run the `tests_32.py` file inside of the `taxsim32` directory.

**Comment by MattHJensen** [comment]
@chusloj, could you update us on the status of this PR?

**Comment by chusloj** [comment]
@MattHJensen The TAXSIM-32 validation process is ready to be merged and the new assumption set `c` can help test QBI-related variables.

**Comment by MattHJensen** [comment]
@chusloj, thanks for all of your work on this PR! Could you check the merge conflicts and then comment on or fix the test failures?

**Comment by Peter-Metz** [comment]
Hi @chusloj this is looking great. Quick question -- are we comparing calculated qbid amounts as part of the validation?

**Comment by chusloj** [comment]
@Peter-Metz,

> are we comparing calculated qbid amounts as part of the validation

No, the TAXSIM-32 suite doesn't currently compare calculated qbid amounts (using `qbided`). I think this is a good addition to the validation suite, but seeing as this PR has been open for quite a while I think it should be merged and then I'll work on qbid amounts in a successive PR.

Also, now that the comparison code is in human-readable Python, it'll be easier for all contributors to chime in.

**Comment by chusloj** [comment]
@MattHJensen All tests passing.

**Comment by chusloj** [comment]
The main time consumer in the validation suite is the FTP file retrieval, so now the file retrieval process will not run during a validation session if `.in.out-taxsim` files already exist.

**Comment by chusloj** [comment]
@MattHJensen @jdebacker This PR is up to date with all tests passing and is ready for review & merge.

**Comment by jdebacker** [comment]
@hdoupe I like this addition to provide validation against TaxSim-32.  The PR generally looks good to me.  Would you mind giving this a thorough review?

**Comment by jdebacker** [comment]
@chusloj You noted this is ready for review.  Can I remove the [WIP] in the title of this PR?

**Comment by chusloj** [comment]
@jdebacker Yes, the branch is no longer WIP.

**Comment by martinholmer** [comment]
A few days ago, when @jdebacker closed Tax-Calculator issue #2513,
@donboyd5 suggested the need for an increased commitment to quality
control in the TaxData process that generates data used by
Tax-Calculator.  He suggested developing methods for "(a) comparing
TaxData to published and forecasted values, and (b) bringing TaxData
(puf.csv) in line with those [published] values".

This comment echos Don's suggestion with respect to testing the
accuracy of the tax calculation logic in Tax-Calculator.  There are
different ways of doing this testing, but one of the most effective is
comparing, record by record, calculated taxes from Tax-Calculator with
calculated taxes for the same sample from NBER's TAXSIM.  This sort of
testing has been done for years using an older version called TAXSIM27.

The objective of this pull request is to update that testing
capability to use TAXSIM32.  This pull request has been open for
almost a year, but the results I present below suggest that completing
this pull request should have a high priority.  Testing Tax-Calculator
against TAXSIM32 is likely to reveal many cases in which the income
tax liability computed by Tax-Calculator differs significantly from
the tax computed by TAXSIM32.  I will present the details of one such
comparison below.

Let me make it clear that I have not reviewed the changes proposed in
this pull request.  But the information I present below could be used
to assess the effectiveness of the new testing tools being proposed in
this pull request.

DETAILS: What I have done is adapt validation tools that I use in my
own work so that those tools can compare, for the same input sample,
the taxes calculated by the Tax-Calculator 3.2.0 CLI and by the
2021-07-01 version of TAXSIM32.  First, I show the summary testing
results, and then, I describe how to download the files needed to
generate the Tax-Calculator and TAXSIM32 results summarized below.

I have used my validation tools to generate a non-representative
sample of 100,000 2019 taxpayers suitable for TAXSIM32 input
(b19.i32.csv).  Then I convert that file so that it can be used as
Tax-Calculator input (b19.itc.csv).  And I also convert b19.i32.csv
into a file that can be used as input by my own model.

TAXSIM32 output is generated by the following command:
<pre>
(py37) validation% taxsim32 < b19.i32.csv > b19.o32.csv
</pre>

And Tax-Calculator output is generate by this command:
<pre>
(py37) validation% tc b19.itc.csv 2019 --reform taxsim_emulation_tc.json
</pre>

Here are the summary results from generating output from the two
models and comparing the output from each against the TAXSIM32 output.
(The expected comparison results, when using my model, are in the
b19.diffs-expect file.)

<pre>
(py37) validation% ./test.sh b19 save
Using local TAXSIM32 executable: Compiled on 07/01/21
BEGIN taxsim execution at Thu Jul 22 08:37:00 EDT 2021
  END taxsim execution at Thu Jul 22 08:37:05 EDT 2021
Validating usita for USI-Tax-Analyzer 2.25.0
BEGIN usita execution at Thu Jul 22 08:37:09 EDT 2021
  END usita execution at Thu Jul 22 08:37:12 EDT 2021
PASSED b19

(py37) validation% cat b19.diffs-expect 
DIFFERENCES FOR OUTVAR ptax=fica  FICA liability
   97490 with 0 cent difference
    2510 with 1 cent difference
DIFFERENCES FOR OUTVAR itax=fitax Federal income tax liability
   98262 with 0 cent difference
    1738 with 1 cent difference

(py37) validation% VALIDATE_TC=1 ./test.sh b19 save
Using existing b19.i32.csv file
Using local TAXSIM32 executable: Compiled on 07/01/21
BEGIN taxsim execution at Thu Jul 22 08:38:05 EDT 2021
  END taxsim execution at Thu Jul 22 08:38:09 EDT 2021
Validating Tax-Calculator 3.2.0 using tc CLI
BEGIN tc execution at Thu Jul 22 08:38:14 EDT 2021
Tax-Calculator startup did not extrapolate your data.
  END tc execution at Thu Jul 22 08:38:46 EDT 2021
Files b19.diffs-actual and b19.diffs-expect differ
FAILED b19

(py37) validation% cat b19.diffs-actual            
DIFFERENCES FOR OUTVAR ptax=fica  FICA liability
   97490 with 0 cent difference
    2510 with 1 cent difference
DIFFERENCES FOR OUTVAR itax=fitax Federal income tax liability
   79645 with 0 cent difference
     753 with 1 cent difference
   19602 with 2+ cent difference
         Record id 87711 has abs(diff)>0.01 with diff= 17143.39
         Record id 37578 has abs(diff)>0.01 with diff= 15881.78
         Record id 42132 has abs(diff)>0.01 with diff= 15537.23
         Record id 51825 has abs(diff)>0.01 with diff= 15480.72
         Record id 91305 has abs(diff)>0.01 with diff= 15443.67
         Record id 70542 has abs(diff)>0.01 with diff= 15372.39
         Record id 4911 has abs(diff)>0.01 with diff= 15135.66
         Record id 98536 has abs(diff)>0.01 with diff= 15098.69
         Record id 33391 has abs(diff)>0.01 with diff= 15024.10
</pre>

So, Tax-Calculator generates an income tax liability that differs from
that generated by TAXSIM32 in almost 20% of the cases.  And many of
the differences are quite large, with some being in the $15,000 to
$17,000 range.  This is why I'm suggesting that testing the accuracy
of the tax calculation logic in Tax-Calculator be given a high priority.

Let me say that, even though I have checked my own work several times,
there could be flaws in the method I developed to translate TAXSIM32
input into Tax-Calculator input.  Please let me know if you find any
problems in the input data translation after you download and inspect
the b19.i32.csv and b19.itc.csv files.  Also, be sure to check that
the taxsim_emulation_tc.json file I used has been correctly specified
for Tax-Calculator.

All three of the files mentioned in the previous paragraph are in a
validation.zip file that can be downloaded by clicking on [this
link](https://drive.google.com/file/d/1DG4k1R5Efec40-64DEs83r3RsNei3KOx/view?usp=sharing).  Here are the contents of that zip file:

<pre>
(py37) validation% unzip -v validation.zip
Archive:  validation.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
12416945  Defl:N  2792324  78% 07-22-2021 08:37 c3058081  b19.i32.csv
13497136  Defl:N  3234787  76% 07-22-2021 08:38 a872fa12  b19.itc.csv
    2285  Defl:N      966  58% 07-19-2021 07:52 25cdecd3  taxsim_emulation_tc.json
--------          -------  ---                            -------
25916366          6028077  77%                            3 files
</pre>

Let me know if you have any problems downloading this zip file.

**Comment by MattHJensen** [comment]
@martinholmer, thanks very much for your note and the effort that you put into the three-way comparison. We are investigating. If you find anything further, please let us know.

**Comment by jdebacker** [comment]
Closing in favor of #2619

**Pull request closed without merging**
