### PR TITLE
TAXSIM-35 Validation, "c" files

### PR DESCRIPTION
**Pull request by jdebacker**
This PR works through the validation of the "c" files in the TAXSIM-35 validation suite.

To validate:

- [x] 2017
- [x] 2018
- [x] 2019
- [x] 2020
- [x] 2021

### CODE REVIEW

**Comment by jdebacker** [comment]
@bodiyang Differences in the "c" file set that are not already documented in the "a" and "b" validation include:

* `c04470`, itemized deductions above the phaseout
  * This variable appears to always be zero in TAXSIM-35
* `c07180`, non-refundable CDCC
  * This may have to do with differences we've noted in how the two calculators output refundable credits vs not (and the correction to make them more similar in 2021 in `process_tc_output.py`)

**Comment by bodiyang** [comment]
For c04470 itemized deduction after phase out, I have conducted manual calculations upon number of records showing differences. I am following[Form 1040 SchA](chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://www.irs.gov/pub/irs-prior/f1040sa--2021.pdf). My manual calculation matches with the Tax-Calculator.

Here are some example records:
(1)
taxsimid 2 year 2021 state mstat 1 page 33 sage depx 0 dep13 0 dep17 0 dep18 0 pwages 51000 swages psemp 223 ssemp 0 dividends 15000 intrec  2000 stcg -9000 ltcg 5000 otherprop 0 nonprop 29000 pensions 39000 gssi 47000 pui 0 sui 7000 transfers rentpaid proptax 7000 otheritem 10000 childcare 0 mortgage 3000 scorp 350000 pbusinc 78000 pprofinc sbusinc sprofinc idtl

c04470 itemized deduction after phase out: Tax-Calculator 13000; Taxsim35 0; Manual Calculation 13000

(2)
taxsimid 30 year 2021 state mstat 2 page 65 sage 72 depx 3 dep13 1 dep17 1 dep18 1 pwages 21000 swages 10000 psemp 216 ssemp 43 dividends 3000 intrec  1000 stcg -9000 ltcg 10000 otherprop 27000 nonprop 20000 pensions 45000 gssi 33000 pui 6000 sui 3000 transfers rentpaid proptax 25000 otheritem 6000 childcare 8000 mortgage 11000 scorp 121000 pbusinc 202000 pprofinc sbusinc 55000 sprofinc idtl

c04470 itemized deduction after phase out: Tax-Calculator 21000; Taxsim35 0; Manual Calculation 21000


(3)
taxsimid 11 year 2018 state mstat 2 page 58 sage 56 depx 4 dep13 2 dep17 2 dep18 2 pwages 27000 swages 82000 psemp 297 ssemp 123 dividends 20000 intrec  11000 stcg -4000 ltcg 5000 otherprop 19000 nonprop 11000 pensions 1000 gssi 17000 pui 0 sui 0 ransfers rentpaid proptax 26000 otheritem 1000 childcare 2000 mortgage 12000 scorp 144000 pbusinc 71000 pprofinc sbusinc 331000 sprofinc idtl

c04470 itemized deduction after phase out: Tax-Calculator 22000; Taxsim35 0; Manual Calculation 22000



My manual calculation for the above records is in [c04470.zip](https://github.com/PSLmodels/Tax-Calculator/files/13991730/c04470.zip)

It is unclear why Taxsim35 showing 0 for the amount of itemized deduction. Looks like there is some phase out setting that zero out the itemized deduction for these records

**Comment by bodiyang** [comment]
@jdebacker `c04470` and `c07180` are all explained. I think that may conclude the file c validation.

**Comment by feenberg** [comment]
.I tried example 1 at http://taxsim.nber.org/taxsim35 and it did show
13,000 in itemized deductions.  The output is attached. How are you
accessing taxsim35?

Daniel Feenberg
617-682-6204

**Pull request merged**
