### PR TITLE
Add instructions for adding/updating a dependency

### PR DESCRIPTION
**Pull request by hdoupe**
Resolves https://github.com/PSLmodels/Tax-Calculator/pull/2423#issuecomment-661045192

### CODE REVIEW

**Comment by hdoupe** [comment]
@MattHJensen @Peter-Metz What do you think about updating this file to look more like a normal Markdown file? It's difficult to link to related files or show code snippets in this format. Also, only using code snippets for the code parts of the instructions will make it easier to copy and paste the bash commands without grabbing the `-->` too.

**Comment by MaxGhenis** [comment]
Should this go in the jupyterbook docs in https://github.com/PSLmodels/Tax-Calculator/tree/master/docs/contributing? I'm not sure why I didn't move this one over.

**Comment by jdebacker** [comment]
@MaxGhenis It's there, right: https://pslmodels.github.io/Tax-Calculator/contributing/contributor_guide.html

**Comment by MaxGhenis** [comment]
@jdebacker not this releasing guide, e.g. this is empty https://pslmodels.github.io/Tax-Calculator/search.html?q=pbrelease

**Comment by hdoupe** [comment]
@MaxGhenis I could go either way on adding it to the jupyterbook docs. It's really only used by the person in charge of releases  and could cause confusion for users if they come across it in the user docs. On the otherhand, it's nice to have one place to go for all docs.

@MattHJensen since you are the primary reader of this doc, do you have any thoughts on this?

**Comment by MattHJensen** [comment]
I think it is helpful for contributors to understand the release process even if they don't manage the release, so I wouldn't mind if RELEASING.md were grouped with other contributor docs in the jupyter book.

**Comment by hdoupe** [comment]
Thanks for the input @MattHJensen. That makes sense to me. I'll update this PR shortly so this info can go in the main documentation.

**Comment by MattHJensen** [comment]
@hdoupe, thanks again for this PR. I just added a WIP tag to the title to indicate that this is waiting on a minor reorg.

**Comment by hdoupe** [comment]
@MattHJensen this is ready to go. I opened #2467 to remind me to move these instructions to the new docs.

**Comment by MattHJensen** [comment]
Thanks @hdoupe. Merging.

**Pull request merged**
