### PR TITLE
Add UBI to benefits totals

### PR DESCRIPTION
**Pull request by jdebacker**
This PR updates the computation of benefits totals to include UBI program benefits.

### CODE REVIEW

**Comment by jdebacker** [comment]
This is ready for review @Peter-Metz @MattHJensen.  

Note, I'm assuming we don't need a consumption benefits scale parameter for UBI since it's a cash transfer.

**Comment by Peter-Metz** [comment]
@jdebacker, thanks a lot for the PR. It looks like `benefit_value_total` and `benefit_cost_total` aren't getting updated with the new implementation because the `BenefitPrograms()` function is using an array of zeros for UBI, as opposed to the calculated amounts. The easiest solution I could come up with is to add a few lines to [_calc_one_year()](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/calculator.py#L1357) which is called during `calc_all()`:

```python
benefit_value_total_ubi = self.array('ubi') + self.array('benefit_value_total')
self.array('benefit_value_total', benefit_value_total_ubi)
benefit_cost_total_ubi = self.array('ubi') + self.array('benefit_cost_total')
self.array('benefit_cost_total', benefit_cost_total_ubi)
```

This solution feels a little hardcoded, but we wouldn't have to modify `calcfunctions.py`.

Also, to avoid double counting when calculating expanded income, we need to remove this [line](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/calcfunctions.py#L1942).

Finally, I was looking at the three Tax-Calc tables -- difference, distribution, and diagnostic -- and it looks like the first two have line items for UBI and benefits totals. We might want to consider adding those variables to the diagnostic table as well.

**Comment by jdebacker** [comment]
@Peter-Metz Thanks for those comments.  Changing this to a WIP while I resolve those issues you raise.

**Comment by jdebacker** [comment]
@Peter-Metz Can you review and see that my latest commits address the issues you raise about computing UBI for benefits totals and adding to the diagnostic tables.  Thanks!

**Comment by jdebacker** [comment]
Also, @Peter-Metz, can you share code you used to find that `benefit_value_total` and `benefit_cost_total` aren't getting updated?  I could add that as a test.

**Comment by Peter-Metz** [comment]
Hey @jdebacker, these latest changes look good to me at first glance, but I'll take a closer look tomorrow. Here's how I tested if `benefits_cost_total` is getting updated:

```python
from taxcalc import *

ubi_ref = {'UBI_21': {2020: 1000}}    

pol = Policy()                                                                             
recs = Records()                                                                           
calc_base = Calculator(pol, recs) 
calc_base.advance_to_year(2020)                                                                
calc_base.calc_all()
                                                          
pol_ubi = Policy()                                                                            
pol_ubi.implement_reform(ubi_ref)
calc_ubi = Calculator(pol_ubi, recs)                                                                                                                      
calc_ubi.advance_to_year(2020)                                                               
calc_ubi.calc_all()

(calc_ubi.weighted_total('ubi') - calc_base.weighted_total('ubi'))/1e9
### 241.02410248

(calc_ubi.weighted_total('benefit_cost_total') - calc_base.weighted_total('benefit_cost_total'))/1e9  
### 0.0

**Comment by jdebacker** [comment]
Thanks @Peter-Metz.  Just added a test that confirms UBI is included in the benefits totals coming out of `Calculator.calc_all()` as you laid it out.

**Comment by Peter-Metz** [comment]
@jdebacker all looks good to me, thanks again for the PR. I'll leave this open for @MattHJensen to review and merge.

**Comment by MattHJensen** [comment]
Thanks a lot for the PR, @jdebacker and review @Peter-Metz. This looks good to me, too. Merging.

**Pull request merged**
