### PR TITLE
Tests for AfterTaxIncome, ExpandIncome, LumpSumTax, and FairShareTax

### PR DESCRIPTION
**Pull request by amshoulders**
Please see the attached file for the test values I used. This PR is ready to be reviewed.

[ASTests.xlsx](https://github.com/PSLmodels/Tax-Calculator/files/6137120/ASTests.xlsx)

### CODE REVIEW

**Comment by jdebacker** [comment]
Tests on Python 3.6 are failing because of conflicts with dependencies.  I think at least one is no longer supported on 3.6 (I had similar issue over in CCC and just dropped testing on 3.6 and 3.7, but never looked into responsible packages).

cc @chusloj

**Comment by chusloj** [comment]
@jdebacker Tests pass on >=3.7 on my [modified branch](https://github.com/chusloj/Tax-Calculator/actions/runs/711995357) of this PR.

cc @MattHJensen

**Comment by chusloj** [comment]
@amshoulders @jdebacker #2584 removed 3.6 from the testing matrix so tests should pass now.

**Comment by jdebacker** [comment]
Thanks @chusloj!

@amshoulders -- if please sync this branch with the master and push. These tests should then pass here.

**Comment by jdebacker** [comment]
@chusloj All tests are passing, but the checks fail due to an error when the profiling is run.  Here's the output around where I think the issue is:

```
taxcalc/tests/test_taxcalcio.py::test_graphs is slower than the current benchmark by 3831.872 ms
103
Traceback (most recent call last):
104
  File "/usr/share/miniconda/envs/taxcalc-dev/bin/pytest", line 11, in <module>
105
    sys.exit(console_main())
106
  File "/usr/share/miniconda/envs/taxcalc-dev/lib/python3.8/site-packages/_pytest/config/__init__.py", line 185, in console_main
107
    code = main()
108
  File "/usr/share/miniconda/envs/taxcalc-dev/lib/python3.8/site-packages/_pytest/config/__init__.py", line 162, in main
109
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
110
  File "/usr/share/miniconda/envs/taxcalc-dev/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
111
    return self._hookexec(self, self.get_hookimpls(), kwargs)
112
  File "/usr/share/miniconda/envs/taxcalc-dev/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
113
    return self._inner_hookexec(hook, methods, kwargs)
114
  File "/usr/share/miniconda/envs/taxcalc-dev/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
115
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
116
  File "/usr/share/miniconda/envs/taxcalc-dev/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
117
    res = hook_impl.function(*args)
118
  File "/usr/share/miniconda/envs/taxcalc-dev/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
119
    raise ex[1].with_traceback(ex[2])
120
  File "/usr/share/miniconda/envs/taxcalc-dev/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
121
    res = hook_impl.function(*args)
122
  File "/usr/share/miniconda/envs/taxcalc-dev/lib/python3.8/site-packages/_pytest/main.py", line 316, in pytest_cmdline_main
123
    return wrap_session(config, _main)
124
  File "/usr/share/miniconda/envs/taxcalc-dev/lib/python3.8/site-packages/_pytest/main.py", line 269, in wrap_session
125
    session.exitstatus = doit(config, session) or 0
126
  File "/usr/share/miniconda/envs/taxcalc-dev/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
127
    return self._hookexec(self, self.get_hookimpls(), kwargs)
128
  File "/usr/share/miniconda/envs/taxcalc-dev/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
129
    return self._inner_hookexec(hook, methods, kwargs)
130
  File "/usr/share/miniconda/envs/taxcalc-dev/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
131
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
132
  File "/usr/share/miniconda/envs/taxcalc-dev/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
133
    gen.send(outcome)
134
  File "/usr/share/miniconda/envs/taxcalc-dev/lib/python3.8/site-packages/_pytest/terminal.py", line 803, in pytest_sessionfinish
135
    outcome.get_result()
136
  File "/usr/share/miniconda/envs/taxcalc-dev/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
137
    raise ex[1].with_traceback(ex[2])
138
  File "/usr/share/miniconda/envs/taxcalc-dev/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
139
    res = hook_impl.function(*args)
140
  File "/home/runner/work/Tax-Calculator/Tax-Calculator/taxcalc/tests/conftest.py", line 165, in pytest_sessionfinish
141
    new_stats_df['time_diff'] = merge_df['time_diff'].values
142
  File "/usr/share/miniconda/envs/taxcalc-dev/lib/python3.8/site-packages/pandas/core/frame.py", line 3163, in __setitem__
143
    self._set_item(key, value)
144
  File "/usr/share/miniconda/envs/taxcalc-dev/lib/python3.8/site-packages/pandas/core/frame.py", line 3242, in _set_item
145
    value = self._sanitize_column(key, value)
146
  File "/usr/share/miniconda/envs/taxcalc-dev/lib/python3.8/site-packages/pandas/core/frame.py", line 3899, in _sanitize_column
147
    value = sanitize_index(value, self.index)
148
  File "/usr/share/miniconda/envs/taxcalc-dev/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 751, in sanitize_index
149
    raise ValueError(
150
ValueError: Length of values (220) does not match length of index (236)
151
taxcalc/tests/test_taxcalcio.py::test_analyze_warnings_print is slower than the current benchmark by 3343.289 ms
```

Any ideas on what's causing the check to fail?

**Comment by chusloj** [comment]
@jdebacker This is a problem I've been having recently with the profiling, not sure what's causing it. I'd say just try a `git commit --allow-empty` to re-trigger the test suite and if that doesn't work I'll revisit the profiling code.

**Comment by jdebacker** [comment]
@amshoulders Please try Jacob's suggestion.  Also, it might work if you click on "Details" for one of the failed tests above and then click on "Re-run jobs" (though not sure if you have that option -- I don't see it, but it might be available to you since you opened this PR).

**Comment by amshoulders** [comment]
Alas, @jdebacker, I tried what @chusloj suggested and still no luck.  I also do not have the option to rerun jobs it seems.

**Comment by chusloj** [comment]
@amshoulders @jdebacker Ok I see the problem, this is definitely my bad. The profiling suite assumes that any provided tests are present in `test_stats_benchmark.csv` which is not true here. I'm going to make a PR to handle this outcome.

**Comment by amshoulders** [comment]
@MattHJensen  All tests are passing so this PR is ready for final review and merge. Thanks!

cc @jdebacker

**Comment by MattHJensen** [comment]
Thanks very much @amshoulders for the contribution, @jdebacker for a review pass, and @chusloj for your help with the test errors. LGTM and merging.

**Pull request merged**
