### PR TITLE
TAXSIM-35 Validation, "a" files

### PR DESCRIPTION
**Pull request by jdebacker**
This PR adds the "expected" files for differences between Tax-Calculator and TAXSIM-35 for the "a" validation sample.  This is the sample with the simplest returns.

We are looking for the differences between each to diff economically insignificant or explain through some difference in the two models.

The following years' files will be added here (and checked off below when differences are explained/resolved):
- [x] 2017
- [x] 2018
- [x] 2019
  - [x] 2 obs with diffs for `iitax` of $196 -- seems to come from eitc diff (note, the max diff in the eitc comes from same record as max offs in mtr)
- [x] 2020
  - [x] 133 obs with differing `rrc` (this may be due to TAXSIM-35 not counting the Jan/March 2021 RRC amounts in 2020)
  - [x] 9 obs with differing `eitc`, up to 75.82
  - [x] 62 obs with differing `mtr_inctax`
- [x] 2021
  - [x] `c11070` diff for 502 records - up to 12500
  - [x] `non_refundable_child_odep_credit` diff for 172 obs - up to 4000 (does this relate `rrc` for jan 2021??)
  - [x] 40 recs with diffs in `mtr_inctax` up to 80
  - [x] 104 recs with diff `iitax`, up to 2500

cc @bodiyang

### CODE REVIEW

**Comment by bodiyang** [comment]
the 2019 'a' set: Tax Calculator is correct
 2 obs with diffs for iitax of $196 -- seems to come from eitc diff

- record 348: $0.01 diff in iitax ~ can be ignored (diff might come from rounding rules)

- record 905: $192 diff in iitax ~ $192 diff in eitc
Tax filler's age is 19, not eligible for EITC (childless tax filler's age must be between 25~65 to be eligible for EITC)
EITC amount: Tax-Calculator $0; Taxsim $196 
Tax-Calculator should be right; Taxsim does not consider the EITC age cap

**Comment by bodiyang** [comment]
the 2020 'a' set: 

records iitax diff mainly come from:

- recovery rebate credit
I have manually calculated the records with differences and Tax-Calculator should be correct. The reasons Taxsim showing different results vary 
~ examples including: not counting qualifying children (id 7); taxsim do not differentiate single/head of household filing status (id 31); taxsim not counting EIP2 (if 33); taxsim counts wrong number of child (id 59)

- eitc

- mtr_inctax

**Comment by jdebacker** [comment]
@bodiyang Thanks for documenting these known diffs in this issue.  To keep track of these long-term, I've added a `Differences_Explained.md` file to this PR.

**Comment by jdebacker** [comment]
@bodiyang Thanks for your help. I believe this PR is ready for review and to merge following that.

**Pull request merged**
