### PR TITLE
Complete and correct work for updates to inflation indexed parameters

### PR DESCRIPTION
**Pull request by bodiyang**

### CODE REVIEW

**Comment by jdebacker** [comment]
- [ ] `ALD_BusinessLosses_c` parameter values for 2020-2022
- [ ] `PT_qbid_taxinc_thd` parameter values for 2020 and 2021
- [ ] Check order of years in `current_law_policy.json`
- [x] Fix **headhh** `CG_brk2` value, it should be 469, 050
- [ ] Correct values for `EITC_ps` in years 2020-2022
- [ ] Correct values for `EITC_ps_MarriedJ` in years 2020-2022

**Comment by bodiyang** [comment]
> * [x]  `ALD_BusinessLosses_c` parameter values for 2020-2022
> * [x]  `PT_qbid_taxinc_thd` parameter values for 2020 and 2021
> * [ ]  Check order of years in `current_law_policy.json`
> * [x]  Fix **headhh** `CG_brk2` value, it should be 469, 050
> * [x]  Correct values for `EITC_ps` in years 2020-2022
> * [ ]  Correct values for `EITC_ps_MarriedJ` in years 2020-2022

Have checked the EITC_ps_MarriedJ in years 2020-2022, the value should be correct

**Comment by jdebacker** [comment]
@bodiyang please see my PR to your branch where I create a json file to handle indexed parameter rounding for the round trip reform.

**Comment by jdebacker** [comment]
@bodiyang Let me know if there are any issues with my PR to your branch.  If you think it's ok, let's merge it. Thanks.

**Comment by jdebacker** [comment]
@bodiyang I remaining incorrect parameter values for `EITC_ps_MarriedJ` and just opened a PR to your branch with that fix.

@MattHJensen There's a lot here and I don't want to miss something again.  Can you put another set of eyes on this PR and let me know if there are still years out of order or if we failed to correct anything noted in Issues #2647, #2649, #2651 and now Issue #2655?

**Comment by jdebacker** [comment]
Thanks for your work on this @bodiyang! 

Merging despite a failure when testing on Windows with Python 3.7.  Error looks like an idiosyncratic issue with connecting to Codecov.io

**Pull request merged**
