### PR TITLE
CBO Feb 2023 update

### PR DESCRIPTION
**Pull request by bodiyang**
This PR serves as a follow up work after https://github.com/PSLmodels/taxdata/pull/421

New input data files will be updated in Tax-Calculator to match the update in Tax-Data

### CODE REVIEW

**Comment by bodiyang** [comment]
@jdebacker @MattHJensen I've passed all tests locally (with puf file testing), but seeing failed tests in git actions. Still investigating the issue (my intuition is because of the version of python, pep8 or pycodestyle).

**Comment by bodiyang** [comment]
This PR also solves [the issue](https://github.com/PSLmodels/Tax-Calculator/issues/2679) that ```.append()``` in pandas Dataframe is deprecated and needs to be replaced

**Comment by bodiyang** [comment]
@jdebacker @MattHJensen This PR is ready for review. I have passed all tests locally (with PUF), also passed all online git actions tests.

**Review by jdebacker — APPROVED** [review]

**Comment by jdebacker** [comment]
LGTM - thanks @bodiyang!  Will leave open until Thursday afternoon in case anyone else has comments.

**Pull request merged**
