### PR TITLE
CBO June 2024 update 

### PR DESCRIPTION
**Pull request by bodiyang**
This PR is to update Tax-Calculator for [the June 2024 CBO baseline update](https://www.cbo.gov/publication/60039).

This is the next step to [the Tax-Data CBO update](https://github.com/PSLmodels/taxdata/pull/446), which updates Tax-Calculator with the new files of PUF weights, ratios.

### CODE REVIEW

**Comment by martinholmer** [comment]
@bodiyang,  I have two questions to start with:

(1) If you are updating using the new CBO 2024+ projections, why are the historical results as far back as 2021 changing?  Why are you revising __HISTORY__?

(2) If you are updating using the new CBO 2024+ projections, why are the 2024+ contents 
 of the `growfactors.csv` file not changing?

**Comment by bodiyang** [comment]
@martinholmer 


For (1): It is because CBO themselves revised the baseline value for the previous years in [June 2024 publication](https://www.cbo.gov/publication/60039). 

Same can be seen in Tax-data's [CBO_baseline.csv](https://github.com/PSLmodels/taxdata/pull/446/files#diff-13543e35fe6d19ac2a34f50d5741a7e3c55d8262ec7e11df99fa2c7a1339e770). This file shows the baseline difference between June 2024 publication and Feb 2024 publication.

**Comment by bodiyang** [comment]
@martinholmer 

I'm also having recheck on growth factors now. Will send updates later

**Comment by martinholmer** [comment]
@bodiyang said in PR #2831:
> For (1): It is because CBO themselves revised the baseline value for the previous years in [June 2024 publication](https://www.cbo.gov/publication/60039).

OK.   What the answer to my question (2)?

**Comment by bodiyang** [comment]
@martinholmer @jdebacker 

There has been a new update from BLS for [CPI](https://api.bls.gov/publicAPI/v1/timeseries/data/CUSR0000SAM) in September, which will affect the growth factor, baseline, ... files. I will make another update in Tax-Data and incorporate the change in this Tax-Calculator PR.

**Comment by martinholmer** [comment]
@bodiyang said:
> There has been a new update from BLS for [CPI](https://api.bls.gov/publicAPI/v1/timeseries/data/CUSR0000SAM) in September, which will affect the growth factor

I don't understand.  Are you saying CBO did not change its economic projections in the June report?  Why are you planning to change __only__ the CPI projection?

Also, if you change the CPI projection in `growfactors.csv`, be sure to do this as described in [taxdata issue #444](https://github.com/PSLmodels/taxdata/issues/444).

**Comment by bodiyang** [comment]
> I don't understand. Are you saying CBO did not change its economic projections in the June report? Why are you planning to change **only** the CPI projection?

CBO changed its economic projections in the June report and it has already been reflected in this June report.

The "CBO update process" in Tax-Data actually also includes the updates from BLS. details can be found at [updatecbo.py](https://github.com/PSLmodels/taxdata/blob/master/puf_stage1/updatecbo.py)

I completed the CBO update process in Tax-Data in August, but I just noticed that BLS has made an update in CPI (which will affect the `CPIM` in `CBO_baseline.csv`) in September. So I decide to make an update for this.

And thanks for bringing up the taxdata issue #444 , I will do the update from there.

**Comment by martinholmer** [comment]
@bodiyang said:
> CBO changed its economic projections in the June report and it has already been reflected in this June report.

This sentence makes no sense to me.   When I look at taxdata `growfactors.csv` it has not changed in eight months even though CBO has new June economic projections.   Why are you not using the new June CBO economic projections?

**Comment by bodiyang** [comment]
> @bodiyang said:
> 
> > CBO changed its economic projections in the June report and it has already been reflected in this June report.
> 
> This sentence makes no sense to me. When I look at taxdata `growfactors.csv` it has not changed in eight months even though CBO has new June economic projections. Why are you not using the new June CBO economic projections?

1. Yes, I am using the new CBO June 2024 update 
2. I am currently working on another update in Tax-Data, which will reflect CBO June 2024 update as well as recent BLS update ~ This update will show change in growth factor. I haven't put it up on github yet, but already get it locally.
3. Last [Tax-Data PR](https://github.com/PSLmodels/taxdata/pull/446/files#): This PR reflect the CBO June 2024, resulting in change of weight files, ratio files ... But it does not result in the change in growth factors. ~~ I didn't conduct a thorough check the reason why growth factor changed there (Maybe the change of baseline is not large enough / or Maybe there is a mistake). However, the update process follow the standard procedure of CBO update, and the produced files passed all tests in Tax-Data & Tax-Calculator. And the projection result looks good, as in [this new report](https://github.com/PSLmodels/taxdata/blob/master/history/reports/taxdata_report_2024-08-20.pdf).

In a conclusion, **I will make another update in Tax-Data with the new changes**, including growth factors, soon. Would make sense to wait a lit bit as I'm finalizing it.

**Comment by bodiyang** [comment]
@jdebacker @martinholmer This PR is ready for review.

Please refer to [the new report](https://github.com/PSLmodels/taxdata/blob/master/history/reports/taxdata_report_2024-11-06.pdf) for updated projections.

**Comment by jdebacker** [comment]
@bodiyang Is this still a work in progress?

**Comment by bodiyang** [comment]
@jdebacker I just tried to merge new updates from master into this PR and saw some new error. Will solve this soon.

**Comment by martinholmer** [comment]
@bodiyang,  When this PR passes all the tests, you can convert it from a draft to ready-to-review.

**Comment by bodiyang** [comment]
@jdebacker This PR is ready for review

**Comment by jdebacker** [comment]
@bodiyang These changes are small, but make sense to me.  And I confirmed all tests, including those using the PUF, do pass for me locally.  Therefore, I am going to merge this PR.

One note:  I still find the PUF file to be off the mark for estimating certain reforms.  E.g., I  have used Tax-Calculator to estimate the 10 year cost of TCJA extension using `reforms/ext.json`.  I have found:
* With `taxcalc` before the changes proposed here: -$2,387B
* With changes in this PR: -$2,376B
* With the TMD file: -$3,211B

For comparison, the [Budget Lab at Yale scores this at](https://budgetlab.yale.edu/research/full-extension-conventional-revenue-score) -$2,816B (under conventional scoring -- so not a static estimate as those above) -- and [JCT/CBO are similar](https://www.cbo.gov/publication/59169) to that.  If one applies similar behavior, I think he TMD score from Tax-Calculator would be very close to those from Yale or JCT.

That is to say, while this PR makes appropriate updates the the files used for the PUF and CPS datasets, these two datasets are still missing some key targets.

**Pull request merged**
