### PR TITLE
Add reform file for President Biden's 2020 campaign proposals

### PR DESCRIPTION
**Pull request by jdebacker**
This PR adds a reform JSON file to capture the provisions in President Biden's 2020 campaign proposals that can be modeled in Tax-Calculator.

The file uses the work of @erinmelly and a similar file was used for the analysis in an [AEI report in June 2020](https://www.aei.org/wp-content/uploads/2020/06/An-Analysis-of-Joe-Bidens-Tax-Proposals.pdf?x91208) by Pomerleau, DeBacker, and Evans.

Included in the above analysis, but excluded here are the following provisions:
```
"CG_TaxAtDeath": {"2021": true},
"CG_exclusion_thd": {"2021": [100000, 200000, 100000, 100000, 200000]},
"IRADC_credit_rt": {"2021": 0.26},
```

These do not work without modifying Tax-Calculator and/or the input data files.

A 10-year revenue estimate from these provisions using the CPS file is:
|         |    2021 |    2022 |    2023 |    2024 |    2025 |     2026 |     2027 |     2028 |     2029 |     2030 |   2021-2030 |
|:--------|--------:|--------:|--------:|--------:|--------:|---------:|---------:|---------:|---------:|---------:|------------:|
| IIT     | 64.5547 | 68.0583 | 69.6535 | 72.9774 | 77.2978 |  40.4184 |  42.6737 |  42.8822 |  45.2362 |  47.4947 |     571.247 |
| Payroll | 68.9383 | 75.0146 | 80.8918 | 87.4692 | 94.8334 | 102.912  | 111.454  | 119.818  | 127.821  | 135.488  |    1004.64  |

### CODE REVIEW

**Comment by MattHJensen** [comment]
@jdebacker, thanks for creating this reform file. I think it will be a great help to the community. But, after giving [these issues](https://github.com/PSLmodels/Tax-Calculator/issues/2445#issuecomment-674168993) more thought, I don't want to keep adding reform files to Tax-Calculator. What do you think about sharing this in a new incubating repo, as a C/S simulation, or both?

**Comment by jdebacker** [comment]
@MattHJensen I'm fine if there is a run on C/S with this reform, but my preference (if reforms are not kept here) is to have a separate repo that creates a reforms package that will be a dependency of Tax-Calculator (so that users of Tax-Calculator will easily have access to reforms).  

Does that package idea still appeal to you?  If so, any suggestions on names for the new repo/package?

**Comment by MattHJensen** [comment]
> Does that package idea still appeal to you? If so, any suggestions on names for the new repo/package?

The package idea makes sense to me, but I will want to think through all of the options before making it a Tax-Calculator dependency. I am eager for it to be easy to use with Tax-Calculator, though. 

Perhaps `reforms` could just be one directory of a `PSLmodels/examples` repo? 
See, e.g., https://github.com/tensorflow/examples.

**Comment by jdebacker** [comment]
> Perhaps reforms could just be one directory of a PSLmodels/examples repo?

@MattHJensen - I like it.

**Comment by Peter-Metz** [comment]
I agree that a separate repo would be great! Just wanted to flag that I seem to remember that the `PT_qbid_*` params were repurposed in Kyle/Erin/Grant's fork. You should be able to get the desired QBID phaseout with `PT_qbid_ps` and `PT_qbid_prt`. Also, when running the reform with the PUF or CPS, it may make sense to flip the `PT_qbid_limit_switch` to `False` to bypass the capital/wage limitations that depend on data that the PUF and CPS don't report.

@erinmelly @grantseiter am I remembering correctly re: the `PT_qbid_*` params?

**Comment by MattHJensen** [comment]
Thanks @Peter-Metz and @jdebacker. I just moved the discussion over here: https://github.com/PSLmodels/examples/issues/1

Closing this PR.

**Pull request closed without merging**
