### PR TITLE
Correct several 2018 EITC parameter values

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request follows up pull request #2212.  When using the 2018 policy parameter values from #2212, Tax-Calculator could not produce the same 2018 EITC amounts as [NBER's TAXSIM-27](https://users.nber.org/~taxsim/taxsim27/).  Further investigation showed that the 2018 values for the `_EITC_ps` and `_EITC_ps_MarriedJ` parameters in #2212 were incorrect.  Changing them to the values described on page 395 of [this IRS publication](https://www.irs.gov/pub/irs-irbs/irb18-10.pdf) eliminated the differences between Tax-Calculator and TAXSIM-27 for the a18 validation sample.

### CODE REVIEW

**Comment by Peter-Metz** [comment]
@martinholmer said:

>can you point us to the appropriate IRS publication?

This information can be found in the [1040 Instructions](https://www.irs.gov/pub/irs-pdf/i1040gi.pdf) in Part 6 of the EIC worksheet (page 52) or the EIC table that begins on page 53.

I am a bit confused by the table in the [url](https://20somethingfinance.com/earned-income-tax-credit/) that you found. The EIC phaseout (`_EITC_ps`) for families with at least one kid begins with incomes of "at least" $18,700, hence I rounded down to $18,690 in [#2212](https://github.com/PSLmodels/Tax-Calculator/pull/2212). I am not sure where to verify the website's $18,660 value.

Similarly, the phaseout for married filing jointly starts with incomes of "at least" $14,200 and $24,350 for 0 kids and 1+ kids respectively. The calculation for `_EITC_ps_MarriedJ` in #2212 was ($14,190 - $8,490 = $5,700) and ($24,340 - $18,690 = $5,650) for 0 kids and 1+ kids respectively.

@martinholmer, let me know if you think I am misinterpreting the parameters and/or the IRS tables.

**Comment by martinholmer** [comment]
@Peter-Metz said in pull request #2220:
> let me know if you think I am misinterpreting the parameters and/or the IRS tables.

The **EIC table** in the IRS forms does not permit exact inference of all the EITC policy parameters.  Yes, the value of `_EITC_c` is clear from the table, but the values of `_EITC_ps` and `_EITC_ps_MarriedJ` are not.  As far as I know, no tax policy microsimulation model uses the EIC tables; they use the same formula that IRS uses to generate the EIC table.

@MattHJensen asked you to prepare a pull request that resolved issue #1694.  Notice that in the initial comment in the #1694 conversation, @MattHJensen provided a link to an IRS publication that included (on pages 9-10) the exact 2018 values of the indexed EITC parameters.  But as the subsequent conversation in #1694 pointed out, that IRS publication was made obsolete by the passage of TCJA.  What you need to find is the IRS publication that shows indexed parameter values for 2018 taking into account the new indexing rules introduced by TCJA.  Perhaps @MattHJensen could provide you with some guidance on how to do that.

**Comment by Peter-Metz** [comment]
@martinholmer, thank you for the explanation. The correct values for `_EITC_ps` and `_EITC_ps_MarriedJ` can be found in [Revenue Procedure 2018-18](https://www.irs.gov/pub/irs-irbs/irb18-10.pdf) on page 395.

**Comment by martinholmer** [comment]
@Peter-Metz said in pull request #2220:
> The correct values for `_EITC_ps` and `_EITC_ps_MarriedJ` can be found in [Revenue Procedure 2018-18](https://www.irs.gov/pub/irs-irbs/irb18-10.pdf) on page 395.

Thanks!

**Pull request merged**
