### PR TITLE
Update TOC for new jb structure and other minor docs updates

### PR DESCRIPTION
**Pull request by MaxGhenis**
This makes the following changes:
* Updates `jupyter-book` table of contents to match their new chapter-oriented structure. This is a necessary change, as their structure revision is backwards-incompatible.
* Mentions that the documentation reflects the latest release, rather than `master` on GitHub. This is correct today, e.g. it still has `CPI_offset`, but if it's intended to reflect `master` I can update that and this note.
* Fixes a broken link on the homepage to the latest release.
* Other minor typo and style issues.

This doesn't currently build due to a TOC issue (I'm guessing I updated something incorrectly - see https://github.com/executablebooks/jupyter-book/issues/839).

### CODE REVIEW

**Comment by jdebacker** [comment]
@MaxGhenis FYI, PR #2441 updates the TOC for the latest Jupyter-Booker also.

**Comment by MaxGhenis** [comment]
Thanks @jdebacker, were you able to build the TOC without the issue I reported in https://github.com/executablebooks/jupyter-book/issues/839? I just compared ours, and they look identical except your new API chapter.

**Comment by jdebacker** [comment]
@MaxGhenis Looks like you had JB version 0.7.1, which doesn't work with the new TOC format.  Try to update your JB version if you still have issues.  I was able to build fine on JB built from master and from 0.7.3.

**Comment by MaxGhenis** [comment]
Ah thanks @jdebacker, I forgot that conda environments also save non-conda package versions. Upgrading to 0.7.3 fixed it. 

This is ready for review. It builds successfully and looks right. I believe the build failures reflect prior failures.

**Comment by MattHJensen** [comment]
Thanks for beautification and fixes @MaxGhenis. Merging.

**Pull request merged**
