### PR TITLE
Update data files to reflect July 2020 changes in CBO economic projections and create new ppp.py

### PR DESCRIPTION
**Pull request by Peter-Metz**
Two components to this PR:
- Incorporates data files produced by PSLmodels/taxdata#332 which prompts updates to inflation-indexed parameters for future years and extrapolated attributes of the filing units in the puf and cps files.
- ~~Creates a new `ppp.py` file. Tax-Calculator's adoption of Paramtools for parameter processing necessitated a new `ppp.py` script due to changes in the way parameters are defined. The functionality is similar. Moving forward, `ppp.py` will need to be run whenever inflation rates are updated in `growfactors.csv`. Thanks to @hdoupe for helping sort out some Paramtools issues.~~

Edit: the changes to `ppp.py` are now handled in #2466  

cc @MattHJensen

### CODE REVIEW

**Comment by hdoupe** [comment]
Looks good @Peter-Metz. I'll get the updates into ParamTools tomorrow.

**Comment by MattHJensen** [comment]
@Peter-Metz, thanks a lot for this PR and working through the ppp.py update for ParamTools (Thanks for your help @hdoupe!). 

My sense -- but I may be misunderstanding  -- is that separating out the ppp.py changes from the data update into two different PRs would allow us to better verify that the ppp.py changes are working as expected. I.e., we should see no test difference in the ppp.py PR. Does that makes sense to you?

**Comment by Peter-Metz** [comment]
>separating out the ppp.py changes from the data update into two different PRs would allow us to better verify that the ppp.py changes are working as expected. I.e., we should see no test

@MattHJensen I made sure of this locally (and actually uncovered a tiny error in pcl -- `II_em_ps` was not using the latest inflation rates for 2026), and there were no changes in values.  The only other difference is that `ppp.py` switches the order of the `values` key and `EIC` key for `EITC_c`, although I don't think this matters.

I'm still happy to open a separate PR. Let me know your preference.

**Comment by MattHJensen** [comment]
> @MattHJensen I made sure of this locally (and actually uncovered a tiny error in pcl -- II_em_ps was not using the latest inflation rates for 2026), and there were no changes in values. The only other difference is that ppp.py switches the order of the values key and EIC key for EITC_c, although I don't think this matters.

> I'm still happy to open a separate PR. Let me know your preference.

Thanks @Peter-Metz, since you are willing to do the separate PR, let's do that for posterity.

**Comment by Peter-Metz** [comment]
@MattHJensen sure thing, see #2466

**Comment by MattHJensen** [comment]
@Peter-Metz, this is looking good, but the PR now has merge conflicts. Could you drop the (new) WIP tag when they are resolved? 

Also, could you help me understand why there are changes to the cpscsv output in this PR?

**Comment by Peter-Metz** [comment]
>Also, could you help me understand why there are changes to the cpscsv output in this PR?

This is due to changes in `growfactors.csv`. I intentionally did not include `growfactors.csv` in #2444 to try to separate changes in results from the new CPS file and from the CBO update.

**Comment by Peter-Metz** [comment]
@MattHJensen conflicts should be resolved

**Comment by MattHJensen** [comment]
> This is due to changes in growfactors.csv. I intentionally did not include growfactors.csv in #2444 to try to separate changes in results from the new CPS file and from the CBO update.

Ok, that's great. 

I am merging. Thanks again for this PR @Peter-Metz and thanks for the data update in TaxData @chusloj and review of the TaxData update @andersonfrailey!

**Pull request merged**
