### PR TITLE
Change in how Python version is specified in several configuration files

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request does a number of things to the Tax-Calculator configuration:
1. Remove python version in `environment.yml` and `conda.recipe/meta.yaml` files
2. Change `.travis.yml` from trusty (ubuntu 14.04) to xenial (ubuntu 16.04) in order to test with Python 3.7
3. Change `appveyor.yml` to test with Python 3.7 under Windows.

So, with this pull request, the Tax-Calculator test suite is run for each GitHub commit under Linux/Python3.6, Windows/Python3.7, and Linux/Python3.7.  This testing under Python 3.7 is the first step towards releasing Tax-Calculator packages for both Python 3.6 and 3.7.

### CODE REVIEW

**Comment by martinholmer** [comment]
@MattHJensen,  Thanks so much for getting the Travis-CI and AppVeyor tests working with Tax-Calculator in its new GitHub organization, PSLmodels.  Everything seems to be working smoothly now.

**Comment by hdoupe** [comment]
@martinholmer, have you tried specifying the python version after updating from the `environment.yml` file?

**Comment by martinholmer** [comment]
@hdoupe said in Tax-Calculator pull request #2154:
> Never mind, looks like you got it!

Yes, but it took quite a few tries shifting through all the conflicting advice on the Internet.
Thanks for following my trials and tribulations on this.  
Now for seeing if we can generate conda packages for Python 3.7.  
Do you know anybody running under Python 3.7 who would be willing to test the new packages?

**Comment by hdoupe** [comment]
Ha, I feel your pain. Getting things to install correctly is a problem I run into about once a month.

I'm willing to test them out. I'll keep an eye on the mailing list to see when they're up.

**Pull request merged**
