### PR TITLE
Add python 3.6 to testing matrix

### PR DESCRIPTION
**Pull request by chusloj**
This PR adds Python `3.6` to the testing suite.

cc @MattHJensen

### CODE REVIEW

**Comment by MattHJensen** [comment]
Thanks @chusloj. Did you mean to include the test_stats.csv in this PR?

**Comment by chusloj** [comment]
@MattHJensen No, this PR is just a one-liner to include Python 3.6 in the testing matrix.

**Comment by MattHJensen** [comment]
> The test_stats_benchmark.csv file is included in #2570.

Looks like it was accidentally included here as well. Could you git rm?

**Comment by chusloj** [comment]
@MattHJensen Thanks for pointing that out. `tests_stats.csv` has been removed.

**Comment by MattHJensen** [comment]
Thanks for the PR @chusloj! Merging.

**Pull request merged**
