### PR TITLE
Use proper var name for section 1250 unrecaptured gains

### PR DESCRIPTION
**Pull request by jdebacker**
This PR addresses Issue #2551 by using the appropriate variable for un-recaptured Section 1250 gains, `e24515`, in the `GainsTax` function. 

CC @nzwiefel @feenberg @MattHJensen

### CODE REVIEW

**Comment by jdebacker** [comment]
These changes validate against TAXSIM27, but do change Tax-Calculator output:

```
(taxcalc-dev) jason.debacker@JDEBACKER validation % sh tests.sh
STARTING WITH VALIDATION TESTS : Thu Feb 11 15:28:24 EST 2021
In taxsim27 directory, executing test.sh using a17, b17, c17 data...
Tax-Calculator startup did not extrapolate your data.
Tax-Calculator startup did not extrapolate your data.
Tax-Calculator startup did not extrapolate your data.
SAME a17
SAME b17
SAME c17
In taxsim27 directory, executing test.sh using a18, b18, c18 data...
Tax-Calculator startup did not extrapolate your data.
Tax-Calculator startup did not extrapolate your data.
Tax-Calculator startup did not extrapolate your data.
SAME a18
SAME b18
SAME c18
FINISHED WITH VALIDATION TESTS : Thu Feb 11 15:35:12 EST 2021
```

I validated against 2013 runs as well.  The largest differences between TAXISM27 and Tax-Calculator in the "a" and "b" files was $1.37.  The "c" files shows larger differences, but results are very similar to differences shown in the `c17.taxdiffs-expect` file.

**Comment by jdebacker** [comment]
Looks like tests pass on here, but the `puf` based tests on my machine are failing due to differences in output.  If my changes look ok, then I can update the expected results files used for those tests.

**Comment by MattHJensen** [comment]
LGTM @jdebacker. Updating expected results is the right next step, and after that I'll merge unless you recommend otherwise. 
Also thanks very much to @nzwiefel for the bug report and to @feenberg for your feedback on the proposed change.

**Comment by jdebacker** [comment]
I've pushed updated "expected" files for the tests.  Everything passes for me locally.  This PR is ready for your final review @MattHJensen.

**Comment by MattHJensen** [comment]
Thanks for this PR @jdebacker! Merging.

**Pull request merged**
