### PR TITLE
Pandas update

### PR DESCRIPTION
**Pull request by jdebacker**
This PR updates the version of the Pandas dependency from `>=1.1.0` to `>=1.2.0` and updates the expected results to accord with the Pandas version bump (which increases the precision of `pandas.read_csv`).

This PR hopes to address issues raised in Issue #2525.

### CODE REVIEW

**Comment by jdebacker** [comment]
Travis CI doesn't seem to be running anymore, so I'm adding a GH Action to do unit tests and code coverage to this PR.

**Comment by jdebacker** [comment]
This PR is now ready for review, resolving all issues in Issue #2525.

In the GH Action that is added, unit tests are run, but for now the `pycodestyle` checks and code coverage reports are removed.  There appears to be some issue with uploading reports to codecov.io, which is happening not just in this repo, but elsewhere, so I believe the issue is on their end.   The coverage reports can be uncommented in this Action when that issue is fixed.

I am unsure why the `pycodestyle` checks fail on the GH Action, but pass locally.  The errors reported in the GH Action point to issues on lines that do not exist in the sources code.  These errors are the following:
```
=================================== FAILURES ===================================
61
______________________________ pycodestyle-check _______________________________
62
/home/runner/work/Tax-Calculator/Tax-Calculator/taxcalc/decorators.py:303:47: E261 at least two spaces before inline comment
63
/home/runner/work/Tax-Calculator/Tax-Calculator/taxcalc/decorators.py:303:80: E501 line too long (101 > 79 characters)
64

65
______________________________ pycodestyle-check _______________________________
66
/home/runner/work/Tax-Calculator/Tax-Calculator/taxcalc/tests/conftest.py:12:1: E302 expected 2 blank lines, found 1
67
/home/runner/work/Tax-Calculator/Tax-Calculator/taxcalc/tests/conftest.py:17:1: E302 expected 2 blank lines, found 1
68

69
______________________________ pycodestyle-check _______________________________
70
/home/runner/work/Tax-Calculator/Tax-Calculator/taxcalc/tests/test_calcfunctions.py:174:77: W291 trailing whitespace
```

**Comment by jdebacker** [comment]
@MattHJensen Do you have the admin rights on the codecov.io account for Tax-Calculator?  Might be issue there (e.g., token expired if it has been a while since you logged on).

**Comment by MattHJensen** [comment]
@jdebacker, I have codecov access and just updated the token. Do you want to add testing back here and see what happens?

**Comment by jdebacker** [comment]
@MattHJensen The codecov upload still doesn't seem to be working.  I had it work again yesterday over in OG-USA, and as far as I can tell, what's done here is exactly the same.

**Comment by MattHJensen** [comment]
@jdebacker, thanks a lot for this PR. I am merging as is and will work on the codecov issue in a separate PR.

**Pull request merged**
