### PR TITLE
Add to the income tax a refundable payroll tax credit (RPTC)

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request implements, as part of the income tax, a Refundable Payroll Tax Credit (RPTC) that can be used to emulate a payroll tax exemption as discussed in issue #2362.

### CODE REVIEW

**Comment by Peter-Metz** [comment]
@martinholmer, thanks again for helping find a solution to #2362 .

This may have been intentional, but I'd like to point out a slight discrepancy in the ways `PEIC` is calculated versus `EITC`. The self-employment income used to calculate earnings for PEIC is adjusted downward by `sey_frac` (the portion of payroll tax that would have been paid by the employer) as shown in these lines:

```
was_plus_sey_p = gross_was_p + max(0., sey_p * sey_frac)
was_plus_sey_s = gross_was_s + max(0., sey_s * sey_frac)
```

On the other hand, the self-employment income used to calculate earnings for EITC is not adjusted by `sey_frac` as seen here:

```
earned = max(0., e00200p + e00200s + sey - c03260)
```

Again, this may have been intentional since the original purpose of the `PEIC` is to emulate a payroll tax exemption, but I wanted to raise the issue.

**Comment by martinholmer** [comment]
@Peter-Metz said in PR #2366:
>This may have been intentional, but I'd like to point out a slight discrepancy in the ways PEIC is calculated versus EITC. The self-employment income used to calculate earnings for PEIC is adjusted downward by `sey_frac` (the portion of payroll tax that would have been paid by the employer) as shown in these lines:
>```
>was_plus_sey_p = gross_was_p + max(0., sey_p * sey_frac)
>was_plus_sey_s = gross_was_s + max(0., sey_s * sey_frac)
>```
>
>On the other hand, the self-employment income used to calculate earnings for EITC is not adjusted by `sey_frac` as seen here:
>```
>earned = max(0., e00200p + e00200s + sey - c03260)
>```
>
>Again, this may have been intentional since the original purpose of the PEIC is to emulate a payroll tax exemption, but I wanted to raise the issue.

@Peter-Metz,  Thanks very much for the close review of the pull request.  
This is exactly the issue I alluded to this morning during our phone call.

Now that I look at this more closely, aren't the `earned` and `was_plus_sey_?` variables the same with respect to the "employer" share of SECA?  Isn't `sey - c03260` that same as `max(0., sey * sey_frac)` (apart from the Medicare difference)?  Or am I confused by my jet lag?

In addition to the difference you mention above, `earned` excludes pension contributions, which are definitely used to compute payroll taxes.

So, because this is not current law or a concrete reform proposal, we're forced to make it up.  I doubt if the requestor has thought through things this far, so it would not be helpful to ask him.  How do you think the PEIC should define earnings?

**Comment by martinholmer** [comment]
@MattHJensen, Can you review PR #2366?  That would be very helpful because you are the person talking to the requestor.

**Comment by Peter-Metz** [comment]
@martinholmer said:

>Now that I look at this more closely, aren't the earned and was_plus_sey_? variables the same with respect to the "employer" share of SECA? Isn't sey - c03260 that same as max(0., sey * sey_frac) (apart from the Medicare difference)?

I see now. I believe your observation is correct. `c03260` calculates the "deductible part of self-employment tax" which is half of self-employment tax owed (`0.5 * setax`), before `sey_frac` is involved. I believe this is the same as simply multiplying `sey_` by `sey_frac`.

Given this equivalence, I think this is an appropriate definition of earnings.

**Comment by martinholmer** [comment]
@Peter-Metz concluded:
> Given this equivalence, I think [the current version] is an appropriate definition of earnings [for the PEIC].

Thanks again for bringing this up.  I needed to think this through more carefully than I done before.

**Comment by MattHJensen** [comment]
@martinholmer, yes, I will review #2366 this morning.

**Comment by MattHJensen** [comment]
This looks good to me other than a couple of cosmetic issues: 

- I found two instances of "positve" -- with only one "i".

- What do you think about calling this a "Personal Payroll Credit" (or something else) rather than a personal earned income credit?  I am concerned about a couple of aspects of the PersonalEIC/peic naming that might confuse our users: 1)  personal EIC and individualized EIC are quite similar. I expect it will be difficult for users to remember which is which. 2) I often hear people refer to "earned income" in reference specific income measure used in the Earned Income Credit. I expect some users will be surprised to learn that the PersonalEIC uses a completely different -- not just an individualized "earned income" -- measure of income.

**Comment by martinholmer** [comment]
@MattHJensen said:
> I found two instances of "positve" -- with only one "i".

Where?  I did a recursive grep and did not find any instances:
```
iMac:Tax-Calculator mrh$ grep -r --include="*" positve .
iMac:Tax-Calculator mrh$ 
```

**Comment by MattHJensen** [comment]
@martinholmer, the `notes` for `PEIC_rt` and `PEIC_c` in `policy_current_law.json`.

**Comment by martinholmer** [comment]
@MattHJensen,  I see.  You meant to say I found two instances of "Positve" -- with only one "i".

**Comment by MattHJensen** [comment]
+1 for RPTC and the PR generally. Thanks a lot for your help with user's request @martinholmer and @Peter-Metz.

**Pull request merged**
