### PR TITLE
update environment files

### PR DESCRIPTION
**Pull request by bodiyang**
This PR is to update the environment.yml file by adding version requirement of `fsspec` package.

Some issues appear, when update the taxcalc-dev environment locally (by running`conda env update` command). ~ `pandas` package has constraints with specific version of`fsspec` package.

It is necessary to clarify the version requirement of `fsspec` package to get it work.

### CODE REVIEW

**Comment by jdebacker** [comment]
@bodiyang Is this necessary?

I just removed my existing `taxcalc-dev` environment and then rebuilt it from the `master` branch with `conda env create`. After doing that, I ran `pytest` and received no errors.

**Comment by bodiyang** [comment]
@jdebacker Not sure, may be it's a universal issue might be not. 

On my local machine, I had attempts of (1) remove `taxcalc-dev` and then rebuilt; also (2) update conda env. ~ Both of them show errors. 
After make the change in `environment.yaml` file, things work.

If other users have not experienced similar issues, can put it on a hold.

**Comment by jdebacker** [comment]
@martinholmer -- have you noticed any issues with the `taxcalc-dev` environment of late?

**Comment by martinholmer** [comment]
@jdebacker asked me in PR #2759:
> have you noticed any issues with the `taxcalc-dev` environment of late?

No, none whatsoever.  What is the issue motivating this PR?

**Comment by bodiyang** [comment]
@jdebacker @martinholmer 

If this conda environment update is not a universal issue, we can close this PR / hold it.


Reason why I opened this PR ~ the attached picture is the error I encountered when `conda env update` from the latest pull from Tax-Calc.

I'm only able to get it run by add the `fsspec` requirement in `environment.yaml` file. 
(remove `taxcalc-dev` and reinstall, such attempts did not work) ~ this might be a single case for my local machine though. 

Screenshot 2024-06-14 at 11 55 29 AM

**Comment by martinholmer** [comment]
@bodiyang,  Why is `fsspec` required at all?   What is it used for in Tax-Calculator?

**Comment by jdebacker** [comment]
@martinholmer `fsspec` is a dependency of `pandas`.  Which is probably all the more reason to not list it in the `environment.yml` file with any pin (let `conda` determine which version of `pandas` and `pandas` choose the appropriate dependencies for itself).

@bodiyang In your screenshot, I find it odd that after `conda env update` there is reference to Python 3.9, but then your `python -V` returns 3.11.

I'm thinking your error was due to something unique to your env and will close this PR.  But please report back if you have issues in the future.

**Pull request closed without merging**
