### PR TITLE
Use cases file to replace citations BibTex file

### PR DESCRIPTION
**Pull request by chusloj**
This PR introduces `use_cases.md` as a single, human-readable bibliography to replace the use of `citations.bib` and the need for `zcitations.md` in the TOC within the docs from #2473.

@MattHJensen

### CODE REVIEW

**Comment by chusloj** [comment]
A new preview file is available in #2480.

**Comment by MattHJensen** [comment]
@chusloj, thanks a lot for this PR and apologies for my delayed response.

Could you update for more recent use cases, close other related but now outdated PRs (I believe #2480, #2473), and then ping me again to merge this? 

Also, the filename is good, but it would likely be helpful to title the top of the file "Recorded use cases" Rather than just "Use cases".

**Comment by chusloj** [comment]
- [x] Update for most recent use cases
- [x] Change filename to "_Recorded use cases_"
- [x] Close outdated PRs

@MattHJensen This is ready to merge.

**Comment by chusloj** [comment]
These are the new citations to be added to `use_cases.md`. Updates range from March of this year up to now.

---

- https://www.aei.org/research-products/report/an-analysis-of-joe-bidens-tax-proposals-october-2020-update/
    - Biden tax policy effects, October 2020 update
- https://www.hoover.org/sites/default/files/research/docs/president_bidens_economic_agenda_hassett.pdf
    - Hoover institution report using tax-calculator
- https://www.wsj.com/articles/how-bidens-tax-plan-might-affect-five-american-households-11599739200
    - Richard rubin WSJ article using Tax-calculator
- https://www.aei.org/wp-content/uploads/2020/09/The-tax-burden-on-business-investment-under-Joe-Bidens-tax-proposals.pdf
    - The Tax Burden on Business Investment Under Joe Biden’s Tax Proposals
- https://www.aei.org/wp-content/uploads/2020/06/An-Analysis-of-Joe-Bidens-Tax-Proposals.pdf
    - An Analysis of Joe Biden’s Tax Proposals
- http://covid.ubicenter.org/fpuc.html#data
    - UBI Center article using Tax-calculator
- https://www.aei.org/economics/eligible-dependents-in-the-cares-act-and-heroes-act-economic-relief-payments/
    - Eligible dependents in the CARES Act and HEROES Act economic relief payments
- https://www.aei.org/economics/the-care-act-who-will-get-a-rebate-and-how-much/
    - The CARES Act: Who will get a rebate and how much?

**Comment by MattHJensen** [comment]
Thanks @chusloj! I think these are unaccounted for, but sorry if there are any dupes. 

- https://www.aei.org/wp-content/uploads/2020/09/The-tax-burden-on-business-investment-under-Joe-Bidens-tax-proposals.pdf
- https://www.aei.org/economics/how-would-joe-bidens-tax-proposals-impact-your-tax-liability/
- https://medium.com/@ernietedeschi/the-distribution-of-household-rebate-ideas-so-far-2b71a8a19914
- https://medium.com/@ernietedeschi/updated-distribution-of-household-rebate-ideas-so-far-f46360034f9d

I'm happy to include select Twitter and Tax-Brain content, too:

- https://twitter.com/kpomerleau/status/1258497005598453761
- https://compute.studio/PSLmodels/Tax-Brain/46307/
- https://compute.studio/AEIEconomics/ccc-biden/
- https://compute.studio/AEIEconomics/Tax-Cruncher-Biden/
- https://twitter.com/kpomerleau/status/1237439229627699200

**Comment by chusloj** [comment]
@MattHJensen The [new citations](https://github.com/PSLmodels/Tax-Calculator/pull/2494#issuecomment-721076967) you listed have been added to the use cases. I think this is ready to merge.

**Comment by MattHJensen** [comment]
Thanks @chusloj. Very much appreciate your taking the initiative on this and working through a few ideas w/ me on how it would be implemented and updated. The new file ought to be of great help to Tax-Calculator supporters and prospective users. Merging.

**Pull request merged**
