### PR TITLE
Move documentation to Jupyterbook

### PR DESCRIPTION
**Pull request by MaxGhenis**
So far this creates Jupyter and webpage versions of `recipe00` using [`jupinx`](https://jupinx.quantecon.org/) (I'll add more recipes if this looks good). Here's the [Jupyter version](https://nbviewer.jupyter.org/github/MaxGhenis/Tax-Calculator/blob/jupinx/docs/jupinx/_build/jupyter/executed/recipe00.ipynb) and here's a [webpage preview](https://htmlpreview.github.io/?https://github.com/MaxGhenis/Tax-Calculator/blob/jupinx/docs/jupinx/_build/website/jupyter_html/recipe00.html) (though it looks much better when rendering locally, see screenshot below).

A few notes:
* I'm not sure how to run this automatically as part of taxcalc testing, but I believe it's possible given the `Makefile`
* Results are in `docs/jupinx/_build`. Executed notebooks are in the `executed` subfolder. It also creates non-executed versions. The website versions only show executed versions.
* The Bokeh visualization doesn't render in the webpage (filed https://github.com/QuantEcon/jupinx/issues/100).
* I made some other small changes, including dropping `print` statements that are unnecessary in Jupyter, and some minor changes like replacing `from taxcalc import *` with `import taxcalc as tc`, making constants uppercase, and loading the reform file from the web so that the notebook can be executed without downloading anything.

image

### CODE REVIEW

**Comment by MaxGhenis** [comment]
I added the rest of the recipes, which all build fine as executed notebooks and webpages, except `recipe01` which is having an error accessing reforms stored on the web (only when building the webpage, see https://github.com/QuantEcon/jupinx/issues/101).

I made similar minor style changes as I described for `recipe00`.

I think the main to-do is running it as part of CI. It takes about 10 minutes to run, given it's running twice for the notebooks and the webpages (https://github.com/QuantEcon/jupinx/issues/102).

Also wanted to note I think these recipes deserve a reboot separately from moving to notebooks. Some of them refer to 2018, or pre-TCJA law, many of the results are printed rows text rather than creating `DataFrame` that could be used elsewhere, there's error-checking that should move to `taxcalc` itself and may confuse new users, etc. But IMO we should start by just recreating what we have here to focus this PR on `jupinx` and then revisit the content in subsequent PRs. Curious what others think.

**Comment by MaxGhenis** [comment]
The `jupinx` developers [shared](https://github.com/QuantEcon/jupinx/issues/100#issuecomment-647079402) that they're moving their development efforts to [jupyterbook.org](http://jupyterbook.org) / [github.com/executablebooks/jupyter-book](http://github.com/executablebooks/jupyter-book). `jupinx` still seems like a stable solution, but `jupyterbook` looks worth exploring as a comprehensive documentation tool, including for example notebooks, with serious ongoing development resources. I'm going to play around with it and follow up here.

**Comment by MaxGhenis** [comment]
After trying `jupyterbook` on a few projects, including [maxghenis.com/microdf](http://maxghenis.com/microdf), I think this is the way to go. It's easy to use, produces beautiful websites, is feature-rich and growing (they just added the ability to open notebook pages in Colab), and super open-source-oriented (e.g. it's easy to add GitHub icons to invite viewers to file issues or suggest edits). Its make file is also simple, so could be integrated into testing (they're also working on documenting this better in https://github.com/executablebooks/jupyter-book/issues/513).

While it might be a bit harder to view diffs of notebooks than `rst` files, I like that it sticks to the natural environment of how Jupyter notebooks are created. You can go from drafting a notebook to publishing in just a couple minutes. I suppose we could also use `jupinx` to generate the notebooks that are then fed into `jupyterbook`, but given `jupyterbook` takes care of a main benefit of `jupinx`--running notebooks to ensure they all build as software develops--I think this would be unnecessary overhead.

This could be a potentially major change, also affecting https://pslmodels.github.io/Tax-Calculator. If there's time in tomorrow's meeting hope we can discuss then.

**Comment by MaxGhenis** [comment]
Per today's discussion, I'm repurposing this PR to move the recipes to `jupyterbook` instead of `jupinx`. In subsequent PRs we can consider moving other taxcalc documentation.

**Comment by MaxGhenis** [comment]
The recipes are all done now. Here's a sample (the Bokeh plot is interactive, and the DataFrame rows highlight on hover):

image

I think the biggest question at this point is how to deploy this. The standard way is to use `github.io`, but Tax-Calculator already uses that. Should we create a project to migrate the rest of the site to jupyterbook through a series of PRs, then switch https://pslmodels.github.io/Tax-Calculator over when it's all in?

Some more minor notes:

jupyterbook has the same issue to jupinx stumbling on reading data from the web (https://github.com/executablebooks/jupyter-book/issues/735), so I load reforms locally instead from `docs/jb/recipes/_static`.

It was easier to convert the jupinx-produced `ipynb` files to MyST than convert from jupinx `rst`. I used `jupytext`, which is very simple to use. Specifically I store all notebooks in `docs/jupyter_src` and then call `convert_all.sh` from there.
This is a bit hokey, especially since `jupyterbook` also creates `ipynb` files when it executes, so we could get rid of it, but for now it shows the lineage of the files. A potential workflow for modifying the recipes in the future would be to copy the relevant notebook in `docs/jb/_build/jupyter_execute/recipes` somewhere local, then run `jupytext` to update the MyST file.

**Comment by MaxGhenis** [comment]
I went ahead and translated the existing documentation. This PR now replaces the current `docs` content, and also pulls in `CONTRIBUTING.md`, `WORKFLOW.md`, `NAMING.md`, and `TESTING.md`. Here's a sample of what it looks like:
image

If you'd like to try it out, you can checkout this PR (as an aside, I'm enjoying the GH CLI, which lets you do `gh pr checkout 2420`) and open `docs/_build/html/index.html`.

I think everything is done, except the table of contents in the User guide (below). Before handling that as-is, I was thinking it could be an opportunity to split it into a few sections, e.g. the 6 top-level headings it's broken down into. What do others think?
Screenshot 2020-06-27 at 21 17 21

Tests also need to be adjusted.

As with the recipes, I think some of the documentation content should be revisited for relevance and tone. I left things mostly as-is when converting them, making only minor adjustments largely for internal consistency.

**Comment by MaxGhenis** [comment]
I split the user guide into its sections, looks better I think:
image

Two (related) to-dos left:
1. Make a version of [`make_uguide.py`](https://github.com/PSLmodels/Tax-Calculator/blob/master/docs/make_uguide.py) to generate all the documentation from `policy_current_law.json`. I think this could use some more section headers so users can easily get links for more precise variable groups.
2. Adjust [`test_section_titles`](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/tests/test_policy.py#L598), which checks that section headers from `policy_current_law.json` match those in the documentation. This is the test that's failing right now, since I deleted `uguide.htmx`.

**Comment by MaxGhenis** [comment]
I translated `make_uguide.py` from producing `html` files to producing `md` files, but it's running into issues before then (it doesn't run on master either, e.g. uses deprecated functions like `Policy.clear_state()`). I could use a pointer if anyone was involved in its creation or can intuit its intended behavior.

Here's the error I get:
```
(base) mghenis@penguin:~/Tax-Calculator/docs$ python make_uguide.py
Traceback (most recent call last):
  File "make_uguide.py", line 331, in <module>
    sys.exit(main())
  File "make_uguide.py", line 55, in main
    params_dict = reformat_params()
  File "make_uguide.py", line 103, in reformat_params
    if params[param][idx]['year'] == year:
KeyError: 0
```

`params[param][idx]['year']` is the issue, where:
* `params` is `tc.Policy().metadata()` (it's currently `tc.Policy().specification()`, but that no longer exists and this seems similar)
* `param` is from `for param in params.keys():`, e.g. `BEN_other_repeal`
* `idx` is from `for idx in range(0, len(params[param])):`. I'm not sure what this is supposed to be doing, given this is what `params[param]` looks like:

```
In [16]: params[param]
Out[16]: 
OrderedDict([('long_name', 'Other benefit repeal switch'),
             ('description',
              'Other benefits can be repealed by switching this parameter to true.'),
             ('section_1', 'Benefits'),
             ('section_2', 'Benefit Repeal'),
             ('irs_ref', ''),
             ('notes', ''),
             ('value_yrs', ['2013']),
             ('indexable', False),
             ('indexed', False),
             ('vi_name', ''),
             ('vi_vals', []),
             ('value_type', 'boolean'),
             ('value', False),
             ('valid_values', OrderedDict([('min', False), ('max', True)])),
             ('invalid_minmsg', ''),
             ('invalid_maxmsg', ''),
             ('invalid_action', 'stop'),
             ('compatible_data', OrderedDict([('puf', False), ('cps', True)])),
             ('start_year', '2013')])
```
This is all to generate a `dict` containing the information for each variable, which is then looped through to construct the html/md.

**Comment by hdoupe** [comment]
> @MaxGhenis it looks like you may using on an old version of Tax-Calculator. The parameter that you printed has all of the old attribute names. Perhaps, you have an installed version that is being picked up when you are running make_uguide.py?

I found a bug in ParamTools that shows up when running the `make_uguide.py`. Make sure you are using the newest version: Paramtools 0.14.2.

**Comment by hdoupe** [comment]
@MaxGhenis the new docs look awesome! Thanks for taking the time to revamp them. A couple things I noticed/have questions about:

- Can we add some info to the recipes landing page:
Screenshot from 2020-06-29 10-40-39

- I really like the search functionality. I think users will appreciate being able to quickly look through the expansive TC documentation.

- I like the idea of adding an API ref and see your issues for this (#2421, #2422)

**Comment by Peter-Metz** [comment]
Hey @MaxGhenis, this is looking great! Looks like `make_uguide.py` should now work with the Paramtools release (thanks @hdoupe!), but I wanted to add that `.clear_state()` and `.specification()` are Paramtools functions and not deprecated Tax-Calc functions.

**Comment by MaxGhenis** [comment]
Thanks @hdoupe @Peter-Metz. I was on `taxcalc 2.9.0` (latest) but I'd installed `taxcalc` through the `pslmodels` `conda` channel, not the `taxcalc-dev` environment, so didn't have `paramtools` installed at all. Is there a way for `taxcalc` to check that `paramtools` is installed when calling its functions on `taxcalc` objects? This was a bit cryptic.

It's getting farther with the new `paramtools`, but hitting this:
```
(taxcalc-dev) mghenis@penguin:~/Tax-Calculator/docs$ python make_uguide.py 
Traceback (most recent call last):
  File "make_uguide.py", line 331, in <module>
    sys.exit(main())
  File "make_uguide.py", line 57, in main
    text = policy_params(POLICY_PATH, text, params_dict)
  File "make_uguide.py", line 214, in policy_params
    ptext += policy_param_text(pname, param, params_dict)
  File "make_uguide.py", line 154, in policy_param_text
    if len(params_dict[pname]['values'][0]) == 5:
KeyError: 'values'
```

**Comment by Peter-Metz** [comment]
@MaxGhenis I was able to get the file to run on your branch by changing [this line](https://github.com/MaxGhenis/Tax-Calculator/blob/jupinx/docs/make_uguide.py#L86) to:

```python
pol.set_year(years_long)
```

and changing the import statement to (and getting rid of the various `tc.`):

```python
from taxcalc import *
```

**Comment by MaxGhenis** [comment]
Thanks @Peter-Metz! It "works" now...no actual content in the result but at least no errors haha. Getting closer!

@hdoupe I'll add more to the recipes landing page describing to-be-added buttons to open in Binder and Colab.

**Comment by hdoupe** [comment]
> It "works" now...no actual content in the result but at least no errors haha. Getting closer!

Progress!

> @hdoupe I'll add more to the recipes landing page describing to-be-added buttons to open in Binder and Colab.

Sounds great.

**Comment by MaxGhenis** [comment]
Pretty much done now, here's what it looks like (while hovering over the GitHub button):
image

The only thing that doesn't work right now is opening notebooks in Colab or Binder.
This isn't currently possible since they're built from MyST, though `jupyter-book` may be able to point to a different file (see https://github.com/executablebooks/jupyter-book/issues/752). If need be, we could either remove the buttons for now or supply `ipynb` files instead. We'd also have to add some code to install `taxcalc` from `conda` from Colab to make it run.

Here are some of the changes since my last message:
* Rewrote `make_uguide.py` to work with Markdown files and the simpler template needs (it just stacks the generated info on top of some header info). I also put the `json` info into `DataFrames` to simplify the code and avoid loops (should be faster too).
* Moved `RELEASES.md`, `CHANGES.md`, and `UPGRADING.md` into the docs. I think this means all documentation-like markdown files are now in the docs.
* Modified `test_section_titles` to work with the markdown file.
* Added GitHub and launch buttons, and some text to the recipes homepage.

Here are a couple choices I made that I wasn't sure about, so feedback welcome:
1. File paths and groupings, e.g. the `User guide` section includes everything that's in the [current user guide](https://pslmodels.github.io/Tax-Calculator/uguide.html), but the `Getting started` and `Structural overview` pages are in a separate folder.
2. Splitting up the user guide. It's currently split into six pages, in the same order as the current. Another option would be combining the `Policy parameters` and `Assumption parameters` pages, and/or the `Input variables` and `Output variables` pages.
*Note: `jupyter-book` doesn't "skip" heading levels, so the variables are smaller in the `Policy parameters` page than other pages, since it has more headings. Breaking the others up with headings would help create consistent variable heading sizes.*

**Comment by MaxGhenis** [comment]
Just discovered htmlpreview.github.io, so you can preview the documentation at https://htmlpreview.github.io/?https://github.com/MaxGhenis/Tax-Calculator/blob/jupinx/docs/_build/html/index.html

**Comment by MaxGhenis** [comment]
In https://github.com/executablebooks/jupyter-book/issues/752#issuecomment-653909078 the jupyter-book team said it would be a bit of work to make MyST files render in Colab, so suggested syncing the MyST and ipynb files, and only showing the ipynb files. I did this a simple way, essentially switching what was already there and revising a bash script to convert. `jupytext` can automatically keep files in sync, so that'd be better in the future. For now though, the recipes correctly direct to Colab (links won't work until this PR is submitted, and it'll still require more code to install).

**Comment by MaxGhenis** [comment]
The recipe notebooks now include code to install conda and taxcalc when in Colab. It's in a cell that's hidden from the webpages. Here's an [example](https://colab.research.google.com/github/MaxGhenis/Tax-Calculator/blob/jupinx/docs/recipes/recipe00.ipynb#scrollTo=X-6PsvQdXO2C).

This still won't fully run because the reform files are loaded locally, so that'll either require fixing https://github.com/executablebooks/jupyter-book/issues/735 or some `try/catch` logic to use local files if they exist, otherwise pull from the web.

**Comment by MattHJensen** [comment]
@MaxGhenis, thank you very much for working on this PR! 

When it is ready for review -- which it may already be given your remarks on the PSL call yesterday -- could you leave a new comment providing an overview of the work, updating and and expanding in any useful ways on your [initial comment](https://github.com/PSLmodels/Tax-Calculator/pull/2420#issue-437219635)?

**Comment by chusloj** [comment]
Max, great work on this new documentation. A few things I've noticed:

1. On mobile, the table of contents drop-down menu opens every time I navigate to a new page.
2. When on a page for one of the recipes, downloading the `.ipynb` file redirects to the raw source code. This may be because I'm viewing the documentation on the GitHub `htmlpreview` site.
3. Any search made within the book using the search bar redirects to [this](https://raw.githubusercontent.com/MaxGhenis/Tax-Calculator/jupinx/docs/_build/html/search.html?q=a) page, but again, this may be because I'm viewing the documentation on the GitHub `htmlpreview` site.

**Comment by MaxGhenis** [comment]
@chusloj thanks for these checks, CIL:

> 1. On mobile, the table of contents drop-down menu opens every time I navigate to a new page.

I think this might be a htmlpreview.github.io thing, as it loads correctly with jupyterbook.org and I'm using their normal table of contents template.

> 2. When on a page for one of the recipes, downloading the `.ipynb` file redirects to the raw source code. This may be because I'm viewing the documentation on the GitHub `htmlpreview` site.

This is the normal behavior, e.g. the [jupyterbook docs](https://jupyterbook.org/interactive/interactive.html) link to [this](https://jupyterbook.org/_sources/interactive/interactive.ipynb). You can right-click to save it.
 
> 3. Any search made within the book using the search bar redirects to [this](https://raw.githubusercontent.com/MaxGhenis/Tax-Calculator/jupinx/docs/_build/html/search.html?q=a) random page, but again, this may be because I'm viewing the documentation on the GitHub `htmlpreview` site.

This works correctly when I load the website locally, so I think it is a `htmlpreview` issue.

**Comment by MaxGhenis** [comment]
@MattHJensen sure, here's a summary:
* Creates infrastructure for [`jupyter-book`](http://jupyterbook.org) in the `docs` folder, including a table of contents (specified in `_toc.yml`) and all files produced by `jupyter-book build` (everything in the `_build` folder)
* Moves all `.md` documentation files (except `README.md` in the home folder) to this new structure
* Re-creates `make_uguide.py` to produce `.md` files instead of `.html` files; also splits it out into separate scripts and simplifies the logic by using `DataFrame`s
* Moves all recipes from `.py` scripts and expected `.txt` results into Jupyter notebooks, which are built in the `recipes` folder
* Minor cleanup of recipes and documentation content
* This all replaces the current contents of the `docs` folder

The only remaining issue regards whether to include links for opening recipe notebooks in Binder/Colab, since code to load reforms refers to local files and will fail - see https://github.com/PSLmodels/Tax-Calculator/pull/2420#issuecomment-654394812.

The html would need to be loaded to a `gh-pages` branch to deploy to GitHub Pages. @jdebacker has picked up some tips on that, which he'll be sharing with @rickecon and me tomorrow.

**Comment by MattHJensen** [comment]
@MaxGhenis, thanks for the summary! 

> The only remaining issue regards whether to include links for opening recipe notebooks in Binder/Colab, since code to load reforms refers to local files and will fail - see #2420 (comment).

This sounds like a follow up issue, not something that needs to be resolved before this is merged. Correct? 

> The html would need to be loaded to a gh-pages branch to deploy to GitHub Pages. @jdebacker has picked up some tips on that, which he'll be sharing with @rickecon and me tomorrow.

Is this still the case if we are deploying gh-pages from master branch? See image of settings below. 

[image](https://user-images.githubusercontent.com/8301092/87933780-dc97ec00-ca5b-11ea-8bcc-21372bc63c3d.png)

**Comment by MaxGhenis** [comment]
Per our chat, I've removed Colab and Binder launchers from this PR, and filed #2429 to revisit that once we figure out the issue loading files.

We also discussed the need to at least maintain guidance to re-run recipes before each release, as described in [RELEASING.md](https://github.com/PSLmodels/Tax-Calculator/blob/master/RELEASING.md). @jdebacker could you advise on using the GitHub Actions to build this automatically when merging into `master`? Is there a way to also add it to CI to eliminate this manual release testing step?

**Comment by jdebacker** [comment]
@MaxGhenis Yes, we should be able to create a GH action to re-run the recipes.  I can advise or open a PR to this branch - just let me know your preference.

Question  - why can't you host documentation files in a `/docs` folder with `jupyter-book`?

**Comment by MaxGhenis** [comment]
@jdebacker Since this PR removes old documentation, it'd be best to include the GH Action in this PR.

`jupyter-book` puts the built pages in `_build/html`. There might be workarounds, but I've been going from their documentation that lists only `ghp-import` and GitHub Actions, both using a `gh-pages` branch to deploy.

**Comment by MaxGhenis** [comment]
Oh I misread - yes @jdebacker if you'd be up to open a PR to this branch that'd be great!

**Comment by jdebacker** [comment]
Got it @MaxGhenis.

Before I do that, it might be helpful for you to clean up this branch/PR a bit.  It looks like you are committing a lot of files that are unnecessary to commit (e.g., the build-generated `doctree` files) and files that will be unnecessary if the book is built and deployed automatically (e.g., all the html files).  As an example, you can look at the [Git-Tutorial](https://github.com/PSLmodels/Git-Tutorial) repo, which only includes the necessary source files in the `master` branch.  The built files necessary for displaying the html are push to the `gh-pages` branch.  A workflow like this is nice as you'll only be tracking changes to the source files in the `master` branch.

**Comment by MaxGhenis** [comment]
@jdebacker Sure, I just removed the `_build` folder from this PR and added `docs/_build/` to the `.gitignore`.

**Comment by MattHJensen** [comment]
@MaxGhenis, thanks a great deal for this PR. @jdebacker, @Peter-Metz, @hdoupe, @chusloj, thank you for your contributions to the PR! 

Merging.

**Pull request merged**
