### PR TITLE
Check for existence of reform and assumption json files

### PR DESCRIPTION
**Pull request by chusloj**
This PR adds checks in the `Parameters` method `_read_json_revision` to check for the existence and validity of reform and assumption files. Addresses #2518.

cc @MaxGhenis

### CODE REVIEW

**Comment by MattHJensen** [comment]
Thanks, @chusloj! 

@MaxGhenis, could you take a look at this to see if it resolves #2518 to your liking before I merge?

**Comment by MaxGhenis** [comment]
LGTM, one other nice-to-have might be a test to ensure that passing a nonexistent json throws the specified error. Thanks @chusloj!

**Comment by chusloj** [comment]
@MaxGhenis Good suggestion, I'll implement that and then this PR will be ready to merge.

**Comment by chusloj** [comment]
Implemented new test. Now a non-existent file throws an `OSError`. A line in ` test_read_bad_json_assump_file()` already tests a non-existent assumption file, so it's been changed to scan for an `OSError` as well.

**Comment by hdoupe** [comment]
@chusloj What do you think about throwing a [`FileNotFoundError`](https://docs.python.org/3/library/exceptions.html#FileNotFoundError) instead of an `OSError`? That way the user / program using the Tax-Calculator API has a little more info about what is going on.

**Comment by chusloj** [comment]
@hdoupe `FileNotFoundError` would be more appropriate.

**Comment by MattHJensen** [comment]
Thanks @chusloj for the contribution and @hdoupe and @MaxGhenis for reviews. Merging.

**Pull request merged**
