### PR TITLE
Code changes to model ARPA

### PR DESCRIPTION
**Pull request by codykallen**
This implements the code changes necessary to model the tax changes in the American Rescue Plan Act of 2021, as described in issue #2571. This adds the following policy parameters and their associated logic: 
 - `RRC_c`, `RRC_ps`, `RRC_pe`: Parameters to implement the Recovery Rebate Credit (i.e. $1,400 payments)
 - `UI_em`, `UI_thd`: Parameters to implement the exclusion of UI benefits from taxable income, up to $10,200 for those with AGI below $150,000.
 - `CDCC_ps2`, `CDCC_refundable`: Parameters to implement changes to the CDCC.
 - `CTC_include17`, `CTC_refundable`: Parameters to implement changes to the CTC.

In addition to these new policy parameters and the logic to implement them, I made the following further changes:
 - Created policy parameters `CDCC_frt` and `CDCC_prt`, to replace their hardcoded values in the `F2441` logic.
 - Minor refactoring to the `ChildDepTaxCredit` function to make it easier to implement the CTC refundability. This refactoring removed some unnecessary code but does not change the underlying logic, so the results do not change.
 - Fixed two whitespace errors flagged by `pycodestyle`.

The next steps for this PR are to add the reform file (in progress), and to add tests to provide coverage for the new code.

@MattHJensen, @martinholmer, @grantseiter, @MaxGhenis, @Thirdhuman, @ernietedeschi, @kpomerleau

### CODE REVIEW

**Comment by MattHJensen** [comment]
@codykallen, this is looking great to me upon initial review. I'll leave it open for others to take a look until this (Sunday) evening when I hope to merge.

**Comment by codykallen** [comment]
Per the discussion with @kpomerleau in issue #2571, the newest commit changes how we calculate the number of 17-year-olds eligible for the CTC under ARPA. The previous logic raised the number of CTC-eligible children by 27.3 million in 2021, whereas the new logic raises it by 1.9 million, a much more reasonable result.

**Comment by rickecon** [comment]
It looks like the only test failing in this PR is in the Jupyter Book documentation tests. The error message looks like it has to do with Python 3.9. It says:
```
Specifications:

  - behresp -> python[version='3.6.*|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0']

Your python: python=3.9
```
The `behresp` model is installed in the Jupyter-Book-related GitHub Actions [`check_jupyterbook.yml`](https://github.com/PSLmodels/Tax-Calculator/blob/master/.github/workflows/check_jupyterbook.yml#L25), [`deploy_jupyterbook`](https://github.com/PSLmodels/Tax-Calculator/blob/master/.github/workflows/deploy_jupyterbook.yml#L28), and [`deploy_parameters_docs.yml`](https://github.com/PSLmodels/Tax-Calculator/blob/master/.github/workflows/deploy_parameters_docs.yml#L28).

The testing in these `.yml` docs specifies Python 3.9. However, the [Behavioral-Responses](https://github.com/PSLmodels/Behavioral-Responses) repo from which the `behresp` package is created only tests in the [`.travis.yml`](https://github.com/PSLmodels/Behavioral-Responses/blob/master/.travis.yml) up to Python 3.8 (see [line 6](https://github.com/PSLmodels/Behavioral-Responses/blob/master/.travis.yml#L6)). To fix this error, I recommend either of the following two options:
1. Update the [Behavioral-Responses](https://github.com/PSLmodels/Behavioral-Responses) repository and resulting `behresp` package to run on Python 3.9, or
2. Change the Jupyter-Book-related GitHub Action tests in the Tax-Calculator repo ([`check_jupyterbook.yml`](https://github.com/PSLmodels/Tax-Calculator/blob/master/.github/workflows/check_jupyterbook.yml), [`deploy_jupyterbook`](https://github.com/PSLmodels/Tax-Calculator/blob/master/.github/workflows/deploy_jupyterbook.yml), [`deploy_parameters_docs.yml`](https://github.com/PSLmodels/Tax-Calculator/blob/master/.github/workflows/deploy_parameters_docs.yml)) to run on Python 3.8 rather than 3.9.

cc: @codykallen @MattHJensen @jdebacker

**Comment by MattHJensen** [comment]
@codykallen, thanks again for this big contribution. @jdebacker, @kpomerleau, and @rickecon, thanks for your help with the review process. 

I am going to merge this now since the failing test *should* pass on master thanks to #2575. If it doesn't, we'll make sure it is passing before releasing.

**Comment by MattHJensen** [comment]
Sorry, @codykallen, I saw your latest commit right after merging, and I didn't let the tests pass. They are running on master now. https://github.com/PSLmodels/Tax-Calculator/runs/2112290774

**Comment by MattHJensen** [comment]
Tests passed on master.

**Pull request merged**
