### PR TITLE
Add action for setting up parameters docs

### PR DESCRIPTION
**Pull request by hdoupe**
@MaxGhenis When you get a chance, can you post the commands needed to create the parameters docs? You're also welcome to add commits to this PR with the commands.

Once those are up, I'll try to deploy this on my fork and see if it works.

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Sorry for the delay, it's just `python docs/guide/make/make_uguide.py`

**Comment by hdoupe** [comment]
@MattHJensen #2450 is ready. Hope it works!  :crossed_fingers:

**Comment by MattHJensen** [comment]
@hdoupe, would you mind restating what this new action is going to do, and when?

**Comment by hdoupe** [comment]
It updates the parameter docs after each release is published. This way the parameter docs are stable in between releases even if new parameters are added/removed on the `master` branch.

**Comment by hdoupe** [comment]
The chat logs for a little posterity:
Screenshot from 2020-08-20 13-07-55

**Comment by MattHJensen** [comment]
I'm not sure that I have a problem with this -- still need to think about it -- but I want to clarify: the downside of this approach is that broken docs won't be caught until after the release. At that point, the build will fail and we'll have to scramble to issue a new bugfix release. Is that right?

**Comment by MaxGhenis** [comment]
How about adding it to https://github.com/PSLmodels/Tax-Calculator/blob/master/.github/workflows/check_jupyterbook.yml to avoid Matt's concern?

**Comment by MattHJensen** [comment]
@hdoupe, thanks a lot for your work on this, and @MaxGhenis, thanks for the review and suggestions. 

@hdoupe, drop the WIP tag when this is ready to go and I'll give it a last look and merge.

**Comment by hdoupe** [comment]
@MattHJensen sure thing! Sorry for the delay on getting the updates in. I just added @MaxGhenis's commit. Once the tests pass, this will be good to go.

**Comment by MattHJensen** [comment]
I'm not sure why the linux 3.8 build has been queued for hours. I'm going to restart the tests,

**Comment by MattHJensen** [comment]
Merging!

**Pull request merged**
