### PR TITLE
Add behresp and jupyter-book to environment.yml

### LINKED ISSUE #2426: Add behresp to taxcalc-dev environment
This is necessary to build the recipes.

### LINKED ISSUE #2438: Add jupyter-book to taxcalc-dev environment
Ensures all devs can build the docs. If this is done, the GitHub Action would no longer need to install jupyter-book separately.

### PR DESCRIPTION
**Pull request by MaxGhenis**
Also removes these extra steps from `deploy_jupyterbook.yml`.

Fixes #2426 and fixes #2438.

cc @jdebacker

### CODE REVIEW

**Comment by MaxGhenis** [comment]
This will require rewriting this test:
```
tests_path = '/home/travis/build/PSLmodels/Tax-Calculator/taxcalc/tests'
    def test_for_consistency(tests_path):
        """
        Ensure that there is consistency between environment.yml dependencies
        and conda.recipe/meta.yaml requirements.
        """
        dev_pkgs = set([
            'pytest',
            'pytest-pep8',
            'pytest-xdist',
            'pycodestyle',
            'pylint',
            'coverage',
            "paramtools>=0.14.0"
        ])
        # read conda.recipe/meta.yaml requirements
        meta_file = os.path.join(tests_path, '..', '..',
                                 'conda.recipe', 'meta.yaml')
        with open(meta_file, 'r') as stream:
            meta = yaml.safe_load(stream)
        bld = set(meta['requirements']['build'])
        run = set(meta['requirements']['run'])
        # confirm conda.recipe/meta.yaml build and run requirements are the same
        assert bld == run
        # read environment.yml dependencies
        envr_file = os.path.join(tests_path, '..', '..',
                                 'environment.yml')
        with open(envr_file, 'r') as stream:
            envr = yaml.safe_load(stream)
>       env = set(envr['dependencies'])
E       TypeError: unhashable type: 'dict'
```

**Comment by hdoupe** [comment]
@MaxGhenis Does conda install the `taxcalc` package from anaconda.org when using this `environment.yml` file?

**Comment by MaxGhenis** [comment]
> @MaxGhenis Does conda install the `taxcalc` package from anaconda.org when using this `environment.yml` file?

No, still `pslmodels`:
```
(base) mghenis@penguin:~/PSLmodels/Tax-Calculator$ conda list taxcalc
# packages in environment at /home/mghenis/anaconda3:
#
# Name                    Version                   Build  Channel
taxcalc                   2.9.0                    py37_0    pslmodels
(base) mghenis@penguin:~/PSLmodels/Tax-Calculator$ conda activate taxcalc-dev
(taxcalc-dev) mghenis@penguin:~/PSLmodels/Tax-Calculator$ conda list taxcalc
# packages in environment at /home/mghenis/anaconda3/envs/taxcalc-dev:
#
# Name                    Version                   Build  Channel
taxcalc                   2.9.0                    py37_0    pslmodels
```

**Comment by hdoupe** [comment]
@MaxGhenis Oh, sorry. I should have been more clear. I'm worried that conda will install `taxcalc` from the `pslmodels` channel instead of just using the local version of `taxcalc`. Then when running tests, `py.test` will use the installed `taxcalc` version instead of the local version of `taxcalc`.

**Comment by hdoupe** [comment]
Nevermind, I just talked to @MaxGhenis offline and he reminded me that you can run `pip install -e .` after creating the environment to get back to the local version of taxcalc.

**Pull request closed without merging**
